"""
test_migrate_vbrief.py -- Unit tests for the vBRIEF migration script.

Tests the migration logic in scripts/migrate_vbrief.py which converts
existing Deft projects to the vBRIEF-centric folder structure (RFC #309).

Story: #312 (Phase 2 vBRIEF Architecture Cutover)

Author: agent3 -- 2026-04-13
"""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()

# Import the module under test
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from migrate_vbrief import (  # noqa: E402, I001
    DEPRECATION_SENTINEL,
    LIFECYCLE_FOLDERS,
    _build_project_definition,
    _create_scope_vbrief,
    _create_speckit_scope_vbrief,
    _dependencies_for_item,
    _derive_overview_narrative,
    _edge_nodes,
    _extract_tech_stack,
    _first_prose_paragraph,
    _is_user_customized,
    _parse_prd_narratives,
    _parse_roadmap_items,
    _resolve_repo_url,
    _slugify,
    _speckit_ip_index,
    _speckit_ip_slug,
    migrate,
    migrate_speckit_plan,
)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _make_project(tmp_path: Path, **kwargs) -> Path:
    """Create a minimal Deft project structure for testing."""
    vbrief_dir = tmp_path / "vbrief"
    vbrief_dir.mkdir(exist_ok=True)

    if "spec_vbrief" in kwargs and kwargs["spec_vbrief"] is not None:
        (vbrief_dir / "specification.vbrief.json").write_text(
            json.dumps(kwargs["spec_vbrief"], indent=2), encoding="utf-8"
        )

    if "spec_md" in kwargs and kwargs["spec_md"] is not None:
        (tmp_path / "SPECIFICATION.md").write_text(kwargs["spec_md"], encoding="utf-8")

    if "project_md" in kwargs and kwargs["project_md"] is not None:
        (tmp_path / "PROJECT.md").write_text(kwargs["project_md"], encoding="utf-8")

    if "roadmap_md" in kwargs and kwargs["roadmap_md"] is not None:
        (tmp_path / "ROADMAP.md").write_text(kwargs["roadmap_md"], encoding="utf-8")

    if "prd_md" in kwargs and kwargs["prd_md"] is not None:
        (tmp_path / "PRD.md").write_text(kwargs["prd_md"], encoding="utf-8")

    return tmp_path


SAMPLE_SPEC_VBRIEF = {
    "vBRIEFInfo": {"version": "0.5", "description": "Test spec"},
    "plan": {
        "title": "Test Specification",
        "status": "approved",
        "narratives": {
            "Overview": "A test project for migration.",
            "Architecture": "Simple architecture.",
        },
        "items": [
            {"id": "t1.1", "title": "Task one", "status": "completed"},
        ],
    },
}

SAMPLE_PROJECT_MD = (
    "# Test Project\n\n"
    "## Project Configuration\n\n"
    "**Tech Stack**: Python\n\n"
    "**Generated by**: deft-setup skill\n"
    "**Date**: 2026-04-01\n"
)

SAMPLE_SPEC_MD = (
    "# Test Specification\n\n"
    "A test specification.\n\n"
    "**Generated by**: spec_render.py\n"
)

SAMPLE_ROADMAP_MD = (
    "# Roadmap\n\n"
    "## Phase 1 -- Foundation\n\n"
    "- **#100** -- Add widget support\n"
    "- **#101** -- Fix login bug\n\n"
    "## Phase 2 -- Features\n\n"
    "- **#200** -- Dashboard redesign\n\n"
    "## Completed\n\n"
    "- ~~#50 -- Initial setup~~\n"
)

CUSTOM_PROJECT_MD = (
    "# My Custom Project\n\n"
    "This is entirely custom content with no auto-generated markers.\n"
    "I wrote this by hand.\n"
)

# ===========================================================================
# Unit tests for helper functions
# ===========================================================================

class TestSlugify:
    """Tests for _slugify."""

    def test_basic_slugify(self):
        assert _slugify("Hello World") == "hello-world"

    def test_special_chars_removed(self):
        assert _slugify("Add widget (v2)!") == "add-widget-v2"

    def test_truncation_at_60(self):
        long_title = "a" * 100
        assert len(_slugify(long_title)) <= 60

    def test_multiple_spaces(self):
        assert _slugify("  foo   bar  ") == "foo-bar"

    def test_empty_string(self):
        assert _slugify("") == ""

    def test_underscores_fold_to_hyphens(self):
        """Regression test for Greptile P1: the docstring claims underscores
        collapse to hyphens, but earlier revisions stripped them before the
        replacement pass. Guards against reintroducing the bug."""
        assert _slugify("task_id_foo") == "task-id-foo"
        assert _slugify("foo___bar") == "foo-bar"
        assert _slugify("mixed  spaces_and_underscores") == "mixed-spaces-and-underscores"


class TestIsUserCustomized:
    """Tests for _is_user_customized."""

    def test_auto_generated_not_customized(self):
        content = "Some text\nGenerated by: tool\n"
        assert _is_user_customized(content, ("Generated by",)) is False

    def test_custom_content_is_customized(self):
        content = "Entirely custom content with no markers.\n"
        assert _is_user_customized(content, ("Generated by", "auto-tool")) is True

    def test_empty_content(self):
        assert _is_user_customized("", ("marker",)) is True


class TestParseRoadmapItems:
    """Tests for _parse_roadmap_items."""

    def test_parses_items_correctly(self, tmp_path):
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(SAMPLE_ROADMAP_MD, encoding="utf-8")
        items, phase_descs, completed = _parse_roadmap_items(roadmap)
        assert len(items) == 3
        assert items[0]["number"] == "100"
        assert items[0]["title"] == "Add widget support"
        assert "Phase 1" in items[0]["phase"]

    def test_skips_completed_from_active_items(self, tmp_path):
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(SAMPLE_ROADMAP_MD, encoding="utf-8")
        items, _, _ = _parse_roadmap_items(roadmap)
        numbers = [i["number"] for i in items]
        assert "50" not in numbers

    def test_parses_completed_items(self, tmp_path):
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(SAMPLE_ROADMAP_MD, encoding="utf-8")
        _, _, completed = _parse_roadmap_items(roadmap)
        assert len(completed) >= 1
        assert completed[0]["title"] == "Initial setup"

    def test_missing_file_returns_empty(self, tmp_path):
        items, phase_descs, completed = _parse_roadmap_items(tmp_path / "nonexistent.md")
        assert items == []
        assert phase_descs == {}
        assert completed == []

    def test_empty_file(self, tmp_path):
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text("", encoding="utf-8")
        items, _, _ = _parse_roadmap_items(roadmap)
        assert items == []

    def test_task_based_format(self, tmp_path):
        """Parser must handle - `X.Y.Z` Title format (#381)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n## Phase 1\n\n"
            "- `1.1.1` TypeScript scaffold\n"
            "- `1.1.2` Setup CI pipeline\n",
            encoding="utf-8",
        )
        items, _, _ = _parse_roadmap_items(roadmap)
        assert len(items) == 2
        assert items[0]["title"] == "TypeScript scaffold"
        assert items[0]["task_id"] == "1.1.1"
        assert items[0]["number"] == ""

    def test_bold_task_based_format(self, tmp_path):
        """Parser must handle - **`X.Y.Z`** Title format (#381)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n## Phase 1\n\n"
            "- **`2.3.1`** Database migration\n",
            encoding="utf-8",
        )
        items, _, _ = _parse_roadmap_items(roadmap)
        assert len(items) == 1
        assert items[0]["title"] == "Database migration"
        assert items[0]["task_id"] == "2.3.1"

    def test_generic_fallback_format(self, tmp_path):
        """Parser must handle plain - Title items (#381)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n## Phase 3\n\n"
            "- Code signing\n"
            "- Low-end LLM compatibility testing\n",
            encoding="utf-8",
        )
        items, _, _ = _parse_roadmap_items(roadmap)
        assert len(items) == 2
        assert items[0]["title"] == "Code signing"
        assert items[0]["number"] == ""
        assert "synthetic_id" in items[0]

    def test_phase_descriptions_captured(self, tmp_path):
        """Parser must capture phase description text (#383)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n"
            "## Phase 1 -- Foundation\n\n"
            "Fix reported bugs blocking adoption.\n\n"
            "- **#100** -- Bug fix\n",
            encoding="utf-8",
        )
        _, phase_descs, _ = _parse_roadmap_items(roadmap)
        assert "Phase 1 -- Foundation" in phase_descs
        assert "Fix reported bugs" in phase_descs["Phase 1 -- Foundation"]

    def test_tier_subheadings_captured(self, tmp_path):
        """Parser must capture tier subheadings (#383)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n## Phase 2\n\n"
            "### Tier 1 -- Core\n\n"
            "- **#200** -- Core feature\n",
            encoding="utf-8",
        )
        items, _, _ = _parse_roadmap_items(roadmap)
        assert len(items) == 1
        assert items[0]["tier"] == "Tier 1 -- Core"

    def test_mixed_formats(self, tmp_path):
        """Parser must handle all formats in a single roadmap (#381)."""
        roadmap = tmp_path / "ROADMAP.md"
        roadmap.write_text(
            "# Roadmap\n\n## Phase 1\n\n"
            "- **#100** -- Issue-based item\n"
            "- `1.1.1` Task-based item\n"
            "- Plain text item\n\n"
            "## Completed\n\n"
            "- ~~#50 -- Done item~~\n",
            encoding="utf-8",
        )
        items, _, completed = _parse_roadmap_items(roadmap)
        assert len(items) == 3
        assert len(completed) == 1


class TestExtractTechStack:
    """Tests for _extract_tech_stack (#382)."""

    def test_extracts_bold_label_format(self):
        content = "# Project\n\n**Tech Stack**: Python 3.11, Flask\n"
        assert _extract_tech_stack(content) == "Python 3.11, Flask"

    def test_extracts_section_format(self):
        content = "# Project\n\n## Tech Stack\n\nGo 1.22, Python 3.11\n\n## Other\n"
        assert "Go 1.22" in _extract_tech_stack(content)

    def test_extracts_plain_label_format(self):
        content = "Some text\nTech Stack: Rust, TypeScript\nMore text\n"
        assert _extract_tech_stack(content) == "Rust, TypeScript"

    def test_returns_empty_when_not_found(self):
        content = "# Project\n\nJust some content with no tech stack.\n"
        assert _extract_tech_stack(content) == ""

    def test_case_insensitive(self):
        content = "**tech stack**: Node.js\n"
        assert _extract_tech_stack(content) == "Node.js"


class TestResolveRepoUrl:
    """Tests for _resolve_repo_url."""

    def test_returns_empty_for_none(self):
        assert _resolve_repo_url(None) == ""

    def test_returns_empty_for_no_repo_info(self):
        spec = {"vBRIEFInfo": {"version": "0.5"}, "plan": {}}
        assert _resolve_repo_url(spec) == ""

    def test_extracts_from_repository_field(self):
        spec = {"vBRIEFInfo": {"version": "0.5", "repository": "myorg/myrepo"}, "plan": {}}
        assert _resolve_repo_url(spec) == "https://github.com/myorg/myrepo"

    def test_extracts_from_plan_references(self):
        spec = {
            "vBRIEFInfo": {"version": "0.5"},
            "plan": {
                "references": [
                    {
                        "uri": "https://github.com/org/repo/blob/main/README.md",
                        "type": "x-vbrief/plan",
                    }
                ]
            },
        }
        assert _resolve_repo_url(spec) == "https://github.com/org/repo"


class TestParsePrdNarratives:
    """Tests for _parse_prd_narratives (#397)."""

    def test_parses_space_separated_headings(self):
        content = (
            "# Title\n\n## Problem Statement\n\nA problem.\n\n"
            "## Goals\n\nSome goals.\n"
        )
        result = _parse_prd_narratives(content)
        assert result == {"ProblemStatement": "A problem.", "Goals": "Some goals."}

    def test_parses_camelcase_headings(self):
        content = "## ProblemStatement\n\nA problem.\n\n## UserStories\n\nStories.\n"
        result = _parse_prd_narratives(content)
        assert result["ProblemStatement"] == "A problem."
        assert result["UserStories"] == "Stories."

    def test_ignores_unknown_headings(self):
        content = "## Unknown Section\n\nContent.\n\n## Goals\n\nGoals.\n"
        result = _parse_prd_narratives(content)
        assert len(result) == 1
        assert result["Goals"] == "Goals."

    def test_skips_empty_sections(self):
        content = "## Goals\n\n\n## Requirements\n\nReqs.\n"
        result = _parse_prd_narratives(content)
        assert "Goals" not in result
        assert result["Requirements"] == "Reqs."

    def test_strips_auto_generated_footer(self):
        content = (
            "## Overview\n\nOverview text.\n\n"
            "---\n*This document is auto-generated.*\n"
        )
        result = _parse_prd_narratives(content)
        assert result["Overview"] == "Overview text."

    def test_strips_bold_auto_generated_footer(self):
        content = (
            "## Overview\n\nOverview text.\n\n"
            "---\n**This document is auto-generated.**\n"
        )
        result = _parse_prd_narratives(content)
        assert result["Overview"] == "Overview text."

    def test_returns_empty_for_no_sections(self):
        assert _parse_prd_narratives("Just a paragraph.") == {}

    def test_nfr_and_open_questions(self):
        content = (
            "## Non-Functional Requirements\n\nNFRs here.\n\n"
            "## Open Questions\n\nQuestions here.\n"
        )
        result = _parse_prd_narratives(content)
        assert result["NonFunctionalRequirements"] == "NFRs here."
        assert result["OpenQuestions"] == "Questions here."


class TestBuildProjectDefinition:
    """Tests for _build_project_definition."""

    def test_includes_spec_narratives(self):
        result = _build_project_definition(SAMPLE_SPEC_VBRIEF, None, [])
        narratives = result["plan"]["narratives"]
        assert "Overview" in narratives
        assert narratives["Overview"] == "A test project for migration."

    def test_includes_project_content(self):
        result = _build_project_definition(None, "My project config", [])
        assert result["plan"]["narratives"]["ProjectConfig"] == "My project config"

    def test_extracts_tech_stack_narrative(self):
        """PROJECT-DEFINITION must include 'tech stack' narrative from PROJECT.md (#382)."""
        content = "# Project\n\n**Tech Stack**: Python 3.11, Flask\n"
        result = _build_project_definition(None, content, [])
        assert result["plan"]["narratives"]["tech stack"] == "Python 3.11, Flask"

    def test_includes_scope_items_with_provenance(self):
        items = [{"number": "42", "title": "Test item", "phase": "Phase 1"}]
        result = _build_project_definition(None, None, items)
        plan_items = result["plan"]["items"]
        assert len(plan_items) == 1
        assert plan_items[0]["id"] == "scope-42"
        assert plan_items[0]["references"][0]["type"] == "github-issue"
        assert plan_items[0]["references"][0]["id"] == "#42"

    def test_vbrief_envelope(self):
        result = _build_project_definition(None, None, [])
        assert result["vBRIEFInfo"]["version"] == "0.5"
        assert result["plan"]["title"] == "PROJECT-DEFINITION"
        assert result["plan"]["status"] == "running"

    def test_no_sources_produces_synthesized_overview(self):
        """Post-#417: even with no spec / project / items, the generated
        PROJECT-DEFINITION gets a synthesized Overview so it passes D3."""
        result = _build_project_definition(None, None, [])
        narratives = result["plan"]["narratives"]
        # Only Overview is synthesized; other narrative keys remain absent
        # until a spec_vbrief / project_content source populates them.
        assert set(narratives.keys()) == {"Overview"}, (
            f"Expected only synthesized Overview, got {sorted(narratives)}"
        )
        assert "was not auto-derived" in narratives["Overview"]
        assert result["plan"]["items"] == []


class TestCreateScopeVbrief:
    """Tests for _create_scope_vbrief."""

    def test_basic_scope_vbrief(self):
        item = {"number": "99", "title": "Test feature", "phase": "Phase 1"}
        result = _create_scope_vbrief(item)
        assert result["vBRIEFInfo"]["version"] == "0.5"
        assert result["plan"]["title"] == "Test feature"
        assert result["plan"]["status"] == "pending"
        assert result["plan"]["references"][0]["id"] == "#99"

    def test_origin_provenance(self):
        item = {"number": "123", "title": "Bug fix", "phase": "Phase 2"}
        result = _create_scope_vbrief(item)
        refs = result["plan"]["references"]
        assert len(refs) == 1
        assert refs[0]["type"] == "github-issue"
        assert refs[0]["id"] == "#123"

    def test_origin_provenance_with_repo_url(self):
        item = {"number": "123", "title": "Bug fix", "phase": "Phase 2"}
        result = _create_scope_vbrief(item, repo_url="https://github.com/owner/repo")
        refs = result["plan"]["references"]
        assert refs[0]["url"] == "https://github.com/owner/repo/issues/123"

    def test_tier_narrative_included(self):
        """Scope vBRIEF must include Tier narrative when tier is set (#383)."""
        item = {"number": "99", "title": "Feature", "phase": "Phase 2", "tier": "Tier 1"}
        result = _create_scope_vbrief(item)
        assert result["plan"]["narratives"]["Tier"] == "Tier 1"

    def test_phase_description_narrative_included(self):
        """Scope vBRIEF must include PhaseDescription when provided (#383)."""
        item = {"number": "99", "title": "Feature", "phase": "Phase 1"}
        result = _create_scope_vbrief(item, phase_description="Fix blocking bugs.")
        assert result["plan"]["narratives"]["PhaseDescription"] == "Fix blocking bugs."

    def test_completed_status_parameter(self):
        """Scope vBRIEF must use the status parameter (#383)."""
        item = {"number": "50", "title": "Done", "phase": "Completed"}
        result = _create_scope_vbrief(item, status="completed")
        assert result["plan"]["status"] == "completed"


# ===========================================================================
# Integration tests for migrate()
# ===========================================================================


class TestMigrateLifecycleFolders:
    """Tests for lifecycle folder creation."""

    def test_creates_all_five_folders(self, tmp_path):
        project = _make_project(tmp_path)
        ok, actions = migrate(project)
        assert ok
        for folder in LIFECYCLE_FOLDERS:
            assert (project / "vbrief" / folder).is_dir()

    def test_idempotent_folder_creation(self, tmp_path):
        project = _make_project(tmp_path)
        migrate(project)
        ok, actions = migrate(project)
        assert ok
        skip_count = sum(1 for a in actions if "SKIP  lifecycle folder" in a)
        assert skip_count == 5


class TestMigrateProjectDefinition:
    """Tests for PROJECT-DEFINITION.vbrief.json generation."""

    def test_generates_project_definition(self, tmp_path):
        project = _make_project(
            tmp_path,
            spec_vbrief=SAMPLE_SPEC_VBRIEF,
            project_md=SAMPLE_PROJECT_MD,
        )
        ok, actions = migrate(project)
        assert ok

        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        assert pd_path.exists()

        data = json.loads(pd_path.read_text(encoding="utf-8"))
        assert data["vBRIEFInfo"]["version"] == "0.5"
        assert "Overview" in data["plan"]["narratives"]
        assert "ProjectConfig" in data["plan"]["narratives"]

    def test_idempotent_project_definition(self, tmp_path):
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF)
        migrate(project)
        ok, actions = migrate(project)
        assert ok
        assert any("SKIP  PROJECT-DEFINITION.vbrief.json already exists" in a for a in actions)

    def test_correct_schema_structure(self, tmp_path):
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF)
        migrate(project)

        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        data = json.loads(pd_path.read_text(encoding="utf-8"))

        # Verify vBRIEF v0.5 envelope
        assert "vBRIEFInfo" in data
        assert "plan" in data
        assert "narratives" in data["plan"]
        assert "items" in data["plan"]
        assert data["plan"]["title"] == "PROJECT-DEFINITION"


class TestMigrateRoadmapConversion:
    """Tests for ROADMAP.md item conversion to pending/ vBRIEFs."""

    def test_converts_roadmap_items_to_pending(self, tmp_path):
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        ok, actions = migrate(project)
        assert ok

        pending_dir = project / "vbrief" / "pending"
        vbrief_files = list(pending_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) == 3  # #100, #101, #200

    def test_scope_vbrief_has_origin_provenance(self, tmp_path):
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        migrate(project)

        pending_dir = project / "vbrief" / "pending"
        for fpath in pending_dir.glob("*.vbrief.json"):
            data = json.loads(fpath.read_text(encoding="utf-8"))
            refs = data["plan"].get("references", [])
            assert len(refs) >= 1
            assert refs[0]["type"] == "github-issue"

    def test_filename_includes_issue_number(self, tmp_path):
        """Filenames include issue number to prevent slug collisions."""
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        migrate(project)

        pending_dir = project / "vbrief" / "pending"
        filenames = [f.name for f in pending_dir.glob("*.vbrief.json")]
        # Each filename should contain the issue number
        assert any("100" in fn for fn in filenames)
        assert any("101" in fn for fn in filenames)
        assert any("200" in fn for fn in filenames)

    def test_slug_collision_produces_separate_files(self, tmp_path):
        """Two items with identical titles but different issue numbers create separate files."""
        collision_roadmap = (
            "# Roadmap\n\n"
            "## Phase 1 -- Foundation\n\n"
            "- **#100** -- Add widget support\n"
            "- **#101** -- Add widget support\n"
        )
        project = _make_project(tmp_path, roadmap_md=collision_roadmap)
        ok, actions = migrate(project)
        assert ok

        pending_dir = project / "vbrief" / "pending"
        vbrief_files = list(pending_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) == 2  # Both items should get separate files

    def test_idempotent_roadmap_conversion(self, tmp_path):
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        migrate(project)
        ok, actions = migrate(project)
        assert ok
        create_count = sum(1 for a in actions if a.startswith("CREATE pending/"))
        assert create_count == 0


class TestMigrateCompletedItems:
    """Tests for completed item migration to completed/ (#383)."""

    def test_completed_items_created_in_completed_folder(self, tmp_path):
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        ok, actions = migrate(project)
        assert ok
        completed_dir = project / "vbrief" / "completed"
        vbrief_files = list(completed_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) >= 1

    def test_completed_vbrief_has_completed_status(self, tmp_path):
        project = _make_project(tmp_path, roadmap_md=SAMPLE_ROADMAP_MD)
        migrate(project)
        completed_dir = project / "vbrief" / "completed"
        for fpath in completed_dir.glob("*.vbrief.json"):
            data = json.loads(fpath.read_text(encoding="utf-8"))
            assert data["plan"]["status"] == "completed"

    def test_non_issue_items_migrated(self, tmp_path):
        """Plain text items must create scope vBRIEFs (#381, #383)."""
        roadmap = (
            "# Roadmap\n\n## Phase 3\n\n"
            "- Code signing\n"
            "- Upgrade GitHub Actions to Node.js 24\n"
        )
        project = _make_project(tmp_path, roadmap_md=roadmap)
        ok, actions = migrate(project)
        assert ok
        pending_dir = project / "vbrief" / "pending"
        vbrief_files = list(pending_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) == 2

    def test_task_based_items_migrated(self, tmp_path):
        """Task-based items must create scope vBRIEFs (#381)."""
        roadmap = (
            "# Roadmap\n\n## Phase 1\n\n"
            "- `1.1.1` TypeScript scaffold\n"
        )
        project = _make_project(tmp_path, roadmap_md=roadmap)
        ok, actions = migrate(project)
        assert ok
        pending_dir = project / "vbrief" / "pending"
        vbrief_files = list(pending_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) == 1
        data = json.loads(vbrief_files[0].read_text(encoding="utf-8"))
        assert data["plan"]["title"] == "TypeScript scaffold"

    def test_path_invalid_chars_in_task_id_slugified(self, tmp_path):
        """Task IDs with path-invalid chars must be slugified in filenames.

        Regression test: items like `task update-index -- --repo <id>` caused
        OSError on Windows because <> and spaces passed through to filenames.
        """
        roadmap = (
            "# Roadmap\n\n## Phase 2\n\n"
            "- `task update-index -- --repo <id>` Builds index for a repo\n"
        )
        project = _make_project(tmp_path, roadmap_md=roadmap)
        ok, actions = migrate(project)
        assert ok
        pending_dir = project / "vbrief" / "pending"
        vbrief_files = list(pending_dir.glob("*.vbrief.json"))
        assert len(vbrief_files) == 1
        # Filename must not contain path-invalid characters
        filename = vbrief_files[0].name
        assert "<" not in filename
        assert ">" not in filename
        assert " " not in filename


class TestMigrateTechStackExtraction:
    """Tests for tech stack extraction during migration (#382)."""

    def test_project_definition_includes_tech_stack(self, tmp_path):
        project = _make_project(tmp_path, project_md=SAMPLE_PROJECT_MD)
        ok, actions = migrate(project)
        assert ok
        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        data = json.loads(pd_path.read_text(encoding="utf-8"))
        assert "tech stack" in data["plan"]["narratives"]
        assert "Python" in data["plan"]["narratives"]["tech stack"]


# ===========================================================================
# #417 -- Overview narrative derivation (D3 compliance on v0.19 fixtures)
# ===========================================================================


_V019_SPEC_MD = (
    "# Widget API SPECIFICATION\n\n"
    "## Problem Statement\n\n"
    "Users need a widget API for managing widget lifecycle.\n\n"
    "## Goals\n\n"
    "- CRUD widgets\n"
    "- List by owner\n\n"
    "## Requirements\n\n"
    "- FR-1: POST /widgets creates a widget\n"
)

_V019_PROJECT_MD = (
    "# Project Guidelines\n\n"
    "## Project Configuration\n\n"
    "- Language: Python 3.11\n"
    "- **Tech Stack**: Python 3.11, FastAPI, SQLite\n"
    "- Coverage: >=75%\n"
)


class TestFirstProseParagraph:
    """Tests for the `_first_prose_paragraph` helper (#417)."""

    def test_returns_first_paragraph_after_heading(self):
        content = (
            "# Title\n\n"
            "## Section\n\n"
            "This is the first prose paragraph.\n"
            "Still the first paragraph.\n\n"
            "Second paragraph.\n"
        )
        assert _first_prose_paragraph(content) == (
            "This is the first prose paragraph. Still the first paragraph."
        )

    def test_falls_back_to_h1_when_only_headings_and_lists(self):
        content = (
            "# Widget API SPECIFICATION\n\n"
            "## Goals\n\n"
            "- CRUD widgets\n"
            "- List by owner\n"
        )
        assert _first_prose_paragraph(content) == "Widget API SPECIFICATION"

    def test_skips_fenced_code_blocks(self):
        content = (
            "# Title\n\n"
            "```\n"
            "code line ignored\n"
            "```\n\n"
            "Real prose paragraph.\n"
        )
        assert _first_prose_paragraph(content) == "Real prose paragraph."

    def test_empty_content_returns_empty(self):
        assert _first_prose_paragraph("") == ""

    def test_only_lists_returns_empty_when_no_h1(self):
        content = "- item one\n- item two\n"
        assert _first_prose_paragraph(content) == ""


class TestDeriveOverviewNarrative:
    """Tests for `_derive_overview_narrative` (#417)."""

    def test_prefers_spec_vbrief_overview(self):
        spec = {
            "plan": {"narratives": {"Overview": "Declared overview from spec vBRIEF."}}
        }
        result = _derive_overview_narrative(spec, "IGNORED SPEC MD", "IGNORED PROJECT", 3)
        assert result == "Declared overview from spec vBRIEF."

    def test_derives_from_spec_md_when_spec_vbrief_missing_overview(self):
        result = _derive_overview_narrative(None, _V019_SPEC_MD, None, 0)
        # First prose paragraph under "## Problem Statement" heading.
        assert result == "Users need a widget API for managing widget lifecycle."

    def test_falls_back_to_project_md_when_no_spec(self):
        result = _derive_overview_narrative(None, None, "# Widget\n\nA widget service.\n", 0)
        assert result == "A widget service."

    def test_synthesized_fallback_when_no_sources(self):
        result = _derive_overview_narrative(None, None, None, 5)
        assert "was not auto-derived during migration" in result
        assert "5 scope item(s)" in result

    def test_ignores_deprecation_stub_input(self):
        """A migrated SPECIFICATION.md carrying the sentinel must NOT be mined."""
        sentinel_stub = (
            f"{DEPRECATION_SENTINEL}\n"
            "# SPECIFICATION.md -- DEPRECATED\n\n"
            "See vbrief/.\n"
        )
        result = _derive_overview_narrative(None, sentinel_stub, None, 2)
        # Falls through to the synthesized fallback rather than grabbing
        # "See vbrief/." from the redirect stub.
        assert "was not auto-derived during migration" in result

    def test_empty_spec_vbrief_overview_is_skipped(self):
        """A spec_vbrief whose Overview is an empty string must not short-circuit."""
        spec = {"plan": {"narratives": {"Overview": "   "}}}
        result = _derive_overview_narrative(spec, _V019_SPEC_MD, None, 0)
        assert "widget api" in result.lower()

    def test_build_project_definition_replaces_blank_overview_from_spec_vbrief(
        self, tmp_path
    ):
        """End-to-end: a pre-existing specification.vbrief.json carrying a
        whitespace-only Overview must be replaced by the derived value so the
        generated PROJECT-DEFINITION has a useful narrative and passes D3.

        This covers the integrated path (the _build_project_definition guard
        must be value-aware, not just key-aware) -- unlike the helper-only
        test above which exercises _derive_overview_narrative in isolation.
        """
        blank_spec = {
            "vBRIEFInfo": {"version": "0.5", "description": "Spec"},
            "plan": {
                "title": "Spec",
                "status": "approved",
                "narratives": {"Overview": "   "},
                "items": [],
            },
        }
        result = _build_project_definition(
            spec_vbrief=blank_spec,
            project_content=None,
            scope_items=[],
            spec_md_content=_V019_SPEC_MD,
        )
        narratives = result["plan"]["narratives"]
        # The blank Overview must be replaced, not preserved.
        overview = next(
            narratives[k] for k in narratives if k.lower() == "overview"
        )
        assert overview.strip(), "blank Overview must be replaced, not kept"
        assert "widget api" in overview.lower()


class TestMigrateOverviewNarrative:
    """Regression test for #417 -- PROJECT-DEFINITION must include Overview narrative."""

    def test_v019_fixture_project_definition_has_overview(self, tmp_path):
        """Canonical v0.19 consumer fixture (no spec_vbrief, no Overview section)
        must still produce PROJECT-DEFINITION.vbrief.json with an Overview key.
        """
        project = _make_project(
            tmp_path,
            spec_md=_V019_SPEC_MD,
            project_md=_V019_PROJECT_MD,
        )
        ok, actions = migrate(project)
        assert ok, f"migrate failed: {actions}"

        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        assert pd_path.is_file()
        data = json.loads(pd_path.read_text(encoding="utf-8"))
        narratives = data["plan"]["narratives"]
        # Case-insensitive match to align with D3 validator behavior.
        assert any(k.lower() == "overview" for k in narratives), (
            f"PROJECT-DEFINITION narratives missing Overview (#417). Keys: {sorted(narratives)}"
        )

    def test_overview_derived_from_spec_md_prose(self, tmp_path):
        """When SPECIFICATION.md has a prose paragraph, it becomes the Overview."""
        project = _make_project(tmp_path, spec_md=_V019_SPEC_MD, project_md=_V019_PROJECT_MD)
        migrate(project)
        data = json.loads(
            (project / "vbrief" / "PROJECT-DEFINITION.vbrief.json").read_text(encoding="utf-8")
        )
        # The v0.19 fixture's first prose paragraph (after "## Problem Statement").
        assert data["plan"]["narratives"]["Overview"] == (
            "Users need a widget API for managing widget lifecycle."
        )

    def test_overview_is_synthesized_when_no_markdown_sources(self, tmp_path):
        """No SPECIFICATION.md, no PROJECT.md, no spec_vbrief -> synthesized Overview."""
        project = _make_project(tmp_path)
        ok, _ = migrate(project)
        assert ok

        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        data = json.loads(pd_path.read_text(encoding="utf-8"))
        ov = data["plan"]["narratives"].get("Overview", "")
        assert ov
        assert "was not auto-derived during migration" in ov

    def test_migrated_project_definition_passes_d3_validator(self, tmp_path):
        """End-to-end: after migration on a v0.19 fixture, PROJECT-DEFINITION
        satisfies scripts/vbrief_validate.py D3 (`overview` + `tech stack`).

        Asserts BOTH the specific D3 narrative-key checks (overview / tech
        stack) AND validator exit code 0.  The D3 key assertions make the
        #417 regression intent explicit; the exit-code assertion acts as a
        canary -- if the validator adds a new error rule that fires on this
        fixture the test surfaces it immediately.  ROADMAP.md items without
        origin provenance emit D11 warnings (not errors), so they do not
        affect the exit code.
        """
        project = _make_project(
            tmp_path,
            spec_md=_V019_SPEC_MD,
            project_md=_V019_PROJECT_MD,
            roadmap_md=SAMPLE_ROADMAP_MD,
        )
        ok, _ = migrate(project)
        assert ok

        validate_script = REPO_ROOT / "scripts" / "vbrief_validate.py"
        result = subprocess.run(
            [sys.executable, str(validate_script), "--vbrief-dir", "vbrief"],
            cwd=str(project),
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=60,
        )
        # D3 errors about 'overview' or 'tech stack' must not fire -- this is
        # the specific regression #417 guards against.
        assert "missing expected key 'overview'" not in result.stdout, (
            f"D3 Overview check failed on migrated project (#417 regression).\n"
            f"stdout: {result.stdout}"
        )
        assert "missing expected key 'tech stack'" not in result.stdout, (
            f"D3 tech stack check failed on migrated project.\nstdout: {result.stdout}"
        )
        # Exit code is 0 today because the D3 errors above are the only ones
        # that would fire on this fixture. A non-zero code signals either a
        # regression in the #417 fix or a new validator rule that this test
        # does not yet cover -- either warrants investigation.
        assert result.returncode == 0, (
            f"vbrief_validate.py returned non-zero on post-migration fixture "
            f"(rc={result.returncode}). This may indicate a #417 regression or "
            f"a new validator rule that should be explicitly covered here.\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )


class TestMigrateDeprecationRedirects:
    """Tests for SPECIFICATION.md and PROJECT.md deprecation redirects."""

    def test_spec_md_replaced_with_redirect(self, tmp_path):
        project = _make_project(tmp_path, spec_md=SAMPLE_SPEC_MD)
        ok, actions = migrate(project)
        assert ok

        content = (project / "SPECIFICATION.md").read_text(encoding="utf-8")
        assert DEPRECATION_SENTINEL in content
        assert "DEPRECATED" in content
        assert "PROJECT-DEFINITION.vbrief.json" in content

    def test_project_md_replaced_with_redirect(self, tmp_path):
        project = _make_project(tmp_path, project_md=SAMPLE_PROJECT_MD)
        ok, actions = migrate(project)
        assert ok

        content = (project / "PROJECT.md").read_text(encoding="utf-8")
        assert DEPRECATION_SENTINEL in content
        assert "DEPRECATED" in content

    def test_idempotent_redirect_replacement(self, tmp_path):
        project = _make_project(
            tmp_path, spec_md=SAMPLE_SPEC_MD, project_md=SAMPLE_PROJECT_MD
        )
        migrate(project)
        ok, actions = migrate(project)
        assert ok
        assert any("SKIP  SPECIFICATION.md already has deprecation redirect" in a for a in actions)
        assert any("SKIP  PROJECT.md already has deprecation redirect" in a for a in actions)

    def test_sentinel_is_machine_parseable(self, tmp_path):
        project = _make_project(tmp_path, spec_md=SAMPLE_SPEC_MD)
        migrate(project)

        content = (project / "SPECIFICATION.md").read_text(encoding="utf-8")
        assert content.startswith(DEPRECATION_SENTINEL)


class TestMigrateCustomizationDetection:
    """Tests for user customization detection and preservation."""

    def test_warns_on_custom_project_md(self, tmp_path):
        project = _make_project(tmp_path, project_md=CUSTOM_PROJECT_MD)
        ok, actions = migrate(project)
        assert ok
        assert any("WARNING: PROJECT.md appears user-customized" in a for a in actions)

    def test_preserves_custom_content_in_narratives(self, tmp_path):
        project = _make_project(tmp_path, project_md=CUSTOM_PROJECT_MD)
        migrate(project)

        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        data = json.loads(pd_path.read_text(encoding="utf-8"))
        assert "ProjectConfig" in data["plan"]["narratives"]
        assert "My Custom Project" in data["plan"]["narratives"]["ProjectConfig"]

    def test_auto_generated_not_flagged_as_custom(self, tmp_path):
        project = _make_project(tmp_path, project_md=SAMPLE_PROJECT_MD)
        ok, actions = migrate(project)
        assert ok
        assert not any("WARNING: PROJECT.md appears user-customized" in a for a in actions)


class TestMigrateSpecVbriefPreservation:
    """Tests that existing specification.vbrief.json content is preserved."""

    def test_spec_vbrief_not_deleted(self, tmp_path):
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF)
        migrate(project)
        assert (project / "vbrief" / "specification.vbrief.json").exists()

    def test_spec_vbrief_content_unchanged(self, tmp_path):
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF)
        migrate(project)
        after = (project / "vbrief" / "specification.vbrief.json").read_text(encoding="utf-8")
        assert json.loads(after) == SAMPLE_SPEC_VBRIEF


class TestMigratePrdNarrativeIngestion:
    """Tests for PRD/SPECIFICATION narrative ingestion into spec narratives (#397)."""

    def test_ingests_prd_narratives(self, tmp_path):
        """PRD.md structured sections ingested into specification.vbrief.json."""
        prd = (
            "# PRD\n\n## Problem Statement\n\nCannot reset passwords.\n\n"
            "## Goals\n\n- Password reset via email\n\n"
            "## User Stories\n\nAs a user I want to reset my password.\n\n"
            "## Requirements\n\nMust support OAuth 2.0.\n\n"
            "## Success Metrics\n\n99% success rate.\n"
        )
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF, prd_md=prd)
        ok, actions = migrate(project)
        assert ok
        data = json.loads(
            (project / "vbrief" / "specification.vbrief.json").read_text(encoding="utf-8")
        )
        n = data["plan"]["narratives"]
        assert n["ProblemStatement"] == "Cannot reset passwords."
        assert "Goals" in n
        assert "UserStories" in n
        assert "Requirements" in n
        assert "SuccessMetrics" in n
        # Existing keys preserved
        assert n["Overview"] == "A test project for migration."
        assert n["Architecture"] == "Simple architecture."

    def test_no_regression_without_prd(self, tmp_path):
        """Migration without PRD.md works exactly as before."""
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF)
        ok, actions = migrate(project)
        assert ok
        assert not any("INGEST" in a for a in actions)

    def test_logs_ingested_keys(self, tmp_path):
        """Migration logs which narrative keys were ingested."""
        prd = "# PRD\n\n## Problem Statement\n\nA problem.\n\n## Goals\n\nGoals.\n"
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF, prd_md=prd)
        ok, actions = migrate(project)
        assert ok
        ingest = [a for a in actions if "INGEST" in a]
        assert len(ingest) == 1
        assert "Goals" in ingest[0]
        assert "ProblemStatement" in ingest[0]

    def test_does_not_overwrite_existing_keys(self, tmp_path):
        """Existing vbrief narrative keys not overwritten by PRD content."""
        prd = "# PRD\n\n## Overview\n\nNew overview.\n\n## Goals\n\nGoals.\n"
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF, prd_md=prd)
        ok, actions = migrate(project)
        assert ok
        data = json.loads(
            (project / "vbrief" / "specification.vbrief.json").read_text(encoding="utf-8")
        )
        # Overview preserved from original vbrief, not overwritten
        assert data["plan"]["narratives"]["Overview"] == "A test project for migration."
        assert "Goals" in data["plan"]["narratives"]

    def test_ingests_specification_md_sections(self, tmp_path):
        """SPECIFICATION.md structured sections are ingested."""
        spec_md = (
            "# Spec\n\n## Requirements\n\n10k requests/sec.\n\n"
            "## Non-Functional Requirements\n\nSOC2 compliance.\n"
        )
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF, spec_md=spec_md)
        ok, actions = migrate(project)
        assert ok
        data = json.loads(
            (project / "vbrief" / "specification.vbrief.json").read_text(encoding="utf-8")
        )
        assert "Requirements" in data["plan"]["narratives"]
        assert "NonFunctionalRequirements" in data["plan"]["narratives"]

    def test_creates_spec_vbrief_when_missing(self, tmp_path):
        """Creates specification.vbrief.json from PRD narratives when absent."""
        prd = "# PRD\n\n## Problem Statement\n\nThe problem.\n\n## Goals\n\nGoals.\n"
        project = _make_project(tmp_path, prd_md=prd)
        ok, actions = migrate(project)
        assert ok
        spec_path = project / "vbrief" / "specification.vbrief.json"
        assert spec_path.exists()
        data = json.loads(spec_path.read_text(encoding="utf-8"))
        assert "ProblemStatement" in data["plan"]["narratives"]
        assert "Goals" in data["plan"]["narratives"]

    def test_skips_deprecated_specification_md(self, tmp_path):
        """SPECIFICATION.md with deprecation sentinel is not parsed."""
        spec_md = f"{DEPRECATION_SENTINEL}\n# DEPRECATED\n\n## Goals\n\nGoals.\n"
        project = _make_project(tmp_path, spec_vbrief=SAMPLE_SPEC_VBRIEF, spec_md=spec_md)
        ok, actions = migrate(project)
        assert ok
        assert not any("INGEST" in a for a in actions)


class TestMigrateFoldFailureAbort:
    """Tests that migration aborts when custom content can't be preserved."""

    def test_aborts_on_custom_spec_fold_failure(self, tmp_path):
        """When SPEC is customized but PROJECT-DEFINITION has invalid structure, abort."""
        custom_spec = "# My Custom Spec\nEntirely custom with no markers.\n"
        project = _make_project(tmp_path, spec_md=custom_spec)
        # Write a malformed PROJECT-DEFINITION that will cause fold to fail
        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        pd_path.write_text("not valid json", encoding="utf-8")
        ok, messages = migrate(project)
        assert not ok
        assert any("ERROR" in m for m in messages)
        # Original SPECIFICATION.md should NOT have been overwritten
        content = (project / "SPECIFICATION.md").read_text(encoding="utf-8")
        assert "My Custom Spec" in content

    def test_custom_spec_preserves_in_narratives(self, tmp_path):
        """When SPEC is customized and fold succeeds, content is preserved."""
        custom_spec = "# My Custom Spec\nEntirely custom with no markers.\n"
        project = _make_project(tmp_path, spec_md=custom_spec)
        ok, actions = migrate(project)
        assert ok
        assert any("WARNING: SPECIFICATION.md appears user-customized" in a for a in actions)
        pd_path = project / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
        data = json.loads(pd_path.read_text(encoding="utf-8"))
        assert "SpecificationContent" in data["plan"]["narratives"]


class TestMigrateExistingScopeSkip:
    """Tests for skipping items that already have scope vBRIEFs."""

    def test_skips_item_with_existing_scope_vbrief(self, tmp_path):
        """If an item already has a vBRIEF in a lifecycle folder, skip it."""
        roadmap = "# Roadmap\n\n## Phase 1\n\n- **#42** -- Existing feature\n"
        project = _make_project(tmp_path, roadmap_md=roadmap)
        # Pre-create a scope vBRIEF referencing #42
        pending_dir = project / "vbrief" / "pending"
        pending_dir.mkdir(parents=True, exist_ok=True)
        existing = {
            "vBRIEFInfo": {"version": "0.5"},
            "plan": {
                "title": "Old",
                "status": "pending",
                "references": [{"type": "github-issue", "id": "#42"}],
            },
        }
        (pending_dir / "old-scope.vbrief.json").write_text(
            json.dumps(existing), encoding="utf-8"
        )
        ok, actions = migrate(project)
        assert ok
        assert any("SKIP  #42 already has scope vBRIEF" in a for a in actions)


class TestMigrateRepoUrlIntegration:
    """Tests that repo_url propagates into generated scope vBRIEFs."""

    def test_scope_vbrief_gets_url_from_spec(self, tmp_path):
        """When spec has repository field, scope vBRIEFs get full URLs."""
        spec_with_repo = {
            "vBRIEFInfo": {"version": "0.5", "repository": "myorg/myproject"},
            "plan": {"title": "Test", "status": "approved", "narratives": {}, "items": []},
        }
        roadmap = "# Roadmap\n\n## Phase 1\n\n- **#99** -- Test feature\n"
        project = _make_project(tmp_path, spec_vbrief=spec_with_repo, roadmap_md=roadmap)
        ok, actions = migrate(project)
        assert ok
        pending = project / "vbrief" / "pending"
        for f in pending.glob("*.vbrief.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            refs = data["plan"].get("references", [])
            if refs:
                assert "myorg/myproject" in refs[0].get("url", "")

    def test_scope_vbrief_no_url_without_repo(self, tmp_path):
        """Without repository info, references have id but no url."""
        roadmap = "# Roadmap\n\n## Phase 1\n\n- **#99** -- Test feature\n"
        project = _make_project(tmp_path, roadmap_md=roadmap)
        ok, actions = migrate(project)
        assert ok
        pending = project / "vbrief" / "pending"
        for f in pending.glob("*.vbrief.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            refs = data["plan"].get("references", [])
            if refs:
                assert "url" not in refs[0]
                assert refs[0]["id"] == "#99"


class TestMigrateInvalidInput:
    """Tests for error handling on invalid input."""

    def test_invalid_spec_vbrief_json(self, tmp_path):
        project = _make_project(tmp_path)
        (project / "vbrief" / "specification.vbrief.json").write_text(
            "not valid json{", encoding="utf-8"
        )
        ok, messages = migrate(project)
        assert not ok
        assert any("ERROR" in m for m in messages)


class TestMigrateSubprocessExecution:
    """Tests for the script as a subprocess (CLI interface)."""

    def test_script_runs_successfully(self, tmp_path):
        project = _make_project(tmp_path, project_md=SAMPLE_PROJECT_MD)
        result = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "migrate_vbrief.py"), str(project)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 0
        assert "Migration completed successfully" in result.stdout

    def test_script_reports_actions(self, tmp_path):
        project = _make_project(
            tmp_path,
            spec_vbrief=SAMPLE_SPEC_VBRIEF,
            project_md=SAMPLE_PROJECT_MD,
            roadmap_md=SAMPLE_ROADMAP_MD,
        )
        result = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "migrate_vbrief.py"), str(project)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 0
        assert "CREATE" in result.stdout

    def test_script_nonexistent_dir(self):
        result = subprocess.run(
            [
                sys.executable,
                str(REPO_ROOT / "scripts" / "migrate_vbrief.py"),
                "/nonexistent/path/that/does/not/exist",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 1


# ===========================================================================
# #436 -- speckit Phase 4 plan -> scope vBRIEF translator
# ===========================================================================


def _write_speckit_plan(
    plan_path: Path,
    items: list[dict],
    edges: list[dict] | None = None,
) -> None:
    """Write a speckit-shaped plan.vbrief.json fixture."""
    plan_path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "vBRIEFInfo": {"version": "0.5", "description": "speckit plan fixture"},
        "plan": {
            "title": "speckit IPs",
            "status": "running",
            "items": items,
            "edges": edges or [],
        },
    }
    plan_path.write_text(json.dumps(data, indent=2), encoding="utf-8")


class TestEdgeNodes:
    """Bilingual edge reader: prefer from/to, fall back to source/target."""

    def test_canonical_from_to(self):
        assert _edge_nodes({"from": "a", "to": "b"}) == ("a", "b")

    def test_legacy_source_target(self):
        assert _edge_nodes({"source": "x", "target": "y"}) == ("x", "y")

    def test_from_to_wins_over_source_target(self):
        edge = {"from": "a", "to": "b", "source": "x", "target": "y"}
        assert _edge_nodes(edge) == ("a", "b")

    def test_missing_edge(self):
        assert _edge_nodes({}) == ("", "")

    def test_non_dict_edge(self):
        assert _edge_nodes(None) == ("", "")


class TestDependenciesForItem:
    def test_blocks_edges_yield_dependencies(self):
        edges = [
            {"from": "ip-1", "to": "ip-3", "type": "blocks"},
            {"from": "ip-2", "to": "ip-3", "type": "blocks"},
        ]
        assert _dependencies_for_item("ip-3", edges) == ["ip-1", "ip-2"]

    def test_legacy_edges_yield_dependencies(self):
        edges = [{"source": "ip-1", "target": "ip-2", "type": "blocks"}]
        assert _dependencies_for_item("ip-2", edges) == ["ip-1"]

    def test_non_blocks_edges_ignored(self):
        edges = [{"from": "a", "to": "b", "type": "relates"}]
        assert _dependencies_for_item("b", edges) == []

    def test_no_edges(self):
        assert _dependencies_for_item("ip-1", []) == []


class TestSpeckitIpIndexAndSlug:
    def test_index_from_item_id_tail(self):
        assert _speckit_ip_index({"id": "ip-7", "title": "IP-9: x"}, 99) == 7

    def test_index_from_title_fallback(self):
        assert _speckit_ip_index({"id": "", "title": "IP-9: Something"}, 99) == 9

    def test_index_fallback_position(self):
        assert _speckit_ip_index({"id": "", "title": "Untitled"}, 4) == 4

    def test_slug_strips_ip_prefix(self):
        assert _speckit_ip_slug("IP-3: Implement data layer", "ip-3") == "implement-data-layer"

    def test_slug_falls_back_to_item_id(self):
        assert _speckit_ip_slug("", "ip-7") == "ip-7"


class TestCreateSpeckitScopeVbrief:
    def test_populates_canonical_narratives(self):
        item = {
            "id": "ip-3",
            "title": "IP-3: Implement data layer",
            "narrative": {
                "Description": "Stand up repositories.",
                "Acceptance": "CRUD round-trips pass.",
                "Traces": "FR-1, FR-3, IP-3",
            },
        }
        result = _create_speckit_scope_vbrief(
            item,
            ip_index=3,
            dependencies=["ip-1", "ip-2"],
            spec_ref="../specification.vbrief.json",
        )
        narratives = result["plan"]["narratives"]
        assert narratives["Description"] == "Stand up repositories."
        assert narratives["Acceptance"] == "CRUD round-trips pass."
        assert narratives["Traces"] == "FR-1, FR-3, IP-3"

    def test_dependencies_written_at_plan_level(self):
        item = {"id": "ip-3", "title": "IP-3: X"}
        result = _create_speckit_scope_vbrief(
            item, ip_index=3, dependencies=["ip-1"], spec_ref="../specification.vbrief.json"
        )
        assert result["plan"]["metadata"]["dependencies"] == ["ip-1"]

    def test_reference_links_back_to_spec(self):
        item = {"id": "ip-1", "title": "IP-1: Bootstrap"}
        result = _create_speckit_scope_vbrief(
            item, ip_index=1, dependencies=[], spec_ref="../specification.vbrief.json"
        )
        refs = result["plan"]["references"]
        assert any(
            r.get("type") == "x-vbrief/plan"
            and r.get("url") == "../specification.vbrief.json"
            for r in refs
        )

    def test_status_is_pending(self):
        item = {"id": "ip-1", "title": "IP-1: Bootstrap"}
        result = _create_speckit_scope_vbrief(
            item, ip_index=1, dependencies=[], spec_ref="../specification.vbrief.json"
        )
        assert result["plan"]["status"] == "pending"

    def test_synthesizes_acceptance_when_missing(self):
        item = {"id": "ip-5", "title": "IP-5: Ship"}
        result = _create_speckit_scope_vbrief(
            item, ip_index=5, dependencies=[], spec_ref="../specification.vbrief.json"
        )
        assert "IP-5" in result["plan"]["narratives"]["Acceptance"]


class TestMigrateSpeckitPlan:
    """End-to-end: migrate_speckit_plan emits N scope vBRIEFs in pending/ (#436)."""

    def test_emits_one_scope_vbrief_per_ip(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[
                {"id": "ip-1", "title": "IP-1: Scaffold", "status": "pending"},
                {"id": "ip-2", "title": "IP-2: Data layer", "status": "pending"},
                {"id": "ip-3", "title": "IP-3: API", "status": "pending"},
            ],
            edges=[
                {"from": "ip-1", "to": "ip-2", "type": "blocks"},
                {"from": "ip-2", "to": "ip-3", "type": "blocks"},
            ],
        )
        ok, actions = migrate_speckit_plan(plan_path)
        assert ok, actions
        pending = list((tmp_path / "vbrief" / "pending").glob("*.vbrief.json"))
        assert len(pending) == 3

    def test_filenames_use_3_digit_ip_padding(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[
                {"id": "ip-7", "title": "IP-7: Ship"},
                {"id": "ip-12", "title": "IP-12: Observability"},
            ],
        )
        ok, actions = migrate_speckit_plan(plan_path)
        assert ok, actions
        names = {f.name for f in (tmp_path / "vbrief" / "pending").glob("*.vbrief.json")}
        assert any("-ip007-" in n for n in names)
        assert any("-ip012-" in n for n in names)

    def test_emits_dependencies_from_blocks_edges(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[
                {"id": "ip-1", "title": "IP-1: A"},
                {"id": "ip-2", "title": "IP-2: B"},
            ],
            edges=[{"from": "ip-1", "to": "ip-2", "type": "blocks"}],
        )
        ok, _ = migrate_speckit_plan(plan_path)
        assert ok
        # find the IP-2 scope and check its dependencies metadata
        pending = tmp_path / "vbrief" / "pending"
        target = next(f for f in pending.glob("*.vbrief.json") if "-ip002-" in f.name)
        data = json.loads(target.read_text(encoding="utf-8"))
        assert data["plan"]["metadata"]["dependencies"] == ["ip-1"]

    def test_legacy_edges_translate_correctly(self, tmp_path):
        """Legacy `source/target` edges translate via the bilingual reader."""
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[
                {"id": "ip-1", "title": "IP-1: A"},
                {"id": "ip-2", "title": "IP-2: B"},
            ],
            edges=[{"source": "ip-1", "target": "ip-2", "type": "blocks"}],
        )
        ok, _ = migrate_speckit_plan(plan_path)
        assert ok
        pending = tmp_path / "vbrief" / "pending"
        target = next(f for f in pending.glob("*.vbrief.json") if "-ip002-" in f.name)
        data = json.loads(target.read_text(encoding="utf-8"))
        assert data["plan"]["metadata"]["dependencies"] == ["ip-1"]

    def test_scope_vbrief_has_narratives_and_spec_ref(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[{
                "id": "ip-1",
                "title": "IP-1: Scaffold",
                "narrative": {
                    "Description": "Repo scaffolding.",
                    "Acceptance": "Build passes.",
                    "Traces": "FR-1, IP-1",
                },
            }],
        )
        ok, _ = migrate_speckit_plan(plan_path)
        assert ok
        pending = tmp_path / "vbrief" / "pending"
        target = next(pending.glob("*.vbrief.json"))
        data = json.loads(target.read_text(encoding="utf-8"))
        assert data["plan"]["narratives"]["Description"] == "Repo scaffolding."
        assert data["plan"]["narratives"]["Acceptance"] == "Build passes."
        assert data["plan"]["narratives"]["Traces"] == "FR-1, IP-1"
        refs = data["plan"]["references"]
        assert refs[0]["type"] == "x-vbrief/plan"
        assert "specification.vbrief.json" in refs[0]["url"]

    def test_plan_rewritten_to_session_scaffold(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[{"id": "ip-1", "title": "IP-1: A"}],
        )
        ok, _ = migrate_speckit_plan(plan_path)
        assert ok
        data = json.loads(plan_path.read_text(encoding="utf-8"))
        assert data["plan"]["items"] == []
        assert data["plan"]["status"] == "running"

    def test_missing_items_errors(self, tmp_path):
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(plan_path, items=[])
        ok, messages = migrate_speckit_plan(plan_path)
        assert not ok
        assert any("no items" in m.lower() for m in messages)

    def test_missing_file_errors(self, tmp_path):
        ok, messages = migrate_speckit_plan(tmp_path / "no-such-plan.vbrief.json")
        assert not ok
        assert any("not found" in m.lower() for m in messages)

    def test_subprocess_speckit_plan_flag(self, tmp_path):
        """CLI: `migrate_vbrief.py --speckit-plan <path>` runs the translator."""
        plan_path = tmp_path / "vbrief" / "plan.vbrief.json"
        _write_speckit_plan(
            plan_path,
            items=[{"id": "ip-1", "title": "IP-1: Scaffold"}],
        )
        result = subprocess.run(
            [
                sys.executable,
                str(REPO_ROOT / "scripts" / "migrate_vbrief.py"),
                "--speckit-plan",
                str(plan_path),
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 0, result.stderr
        pending = list((tmp_path / "vbrief" / "pending").glob("*.vbrief.json"))
        assert len(pending) == 1
