#!/usr/bin/env python3
"""
migrate_vbrief.py -- Migrate a Deft project to the vBRIEF-centric document model.

Converts existing SPECIFICATION.md + specification.vbrief.json + PROJECT.md +
ROADMAP.md into the new lifecycle folder structure defined by RFC #309.

Usage:
    uv run python scripts/migrate_vbrief.py [project_root]

    project_root -- path to the project root (default: current working directory)

Exit codes:
    0 -- migration completed successfully
    1 -- migration failed (errors printed to stderr)

Story: #312 (Phase 2 vBRIEF Architecture Cutover)
"""

from __future__ import annotations

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlparse

# Ensure the ``scripts/`` directory is on sys.path so sibling module
# ``_vbrief_build`` is importable whether this file is run as __main__ or
# imported from a test harness that appends the ``scripts/`` path.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _vbrief_build import create_scope_vbrief as _create_scope_vbrief_shared  # noqa: E402
from _vbrief_build import slugify as _slugify_shared  # noqa: E402

# Lifecycle folders per RFC #309 D13
LIFECYCLE_FOLDERS = ("proposed", "pending", "active", "completed", "cancelled")

# Deprecation redirect sentinel per Story S (#334)
DEPRECATION_SENTINEL = "<!-- deft:deprecated-redirect -->"

# Known auto-generated markers for detecting user customization
_SPEC_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
    "spec_render.py",
)
_PROJECT_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
)

# Date for migration-created vBRIEF filenames (D7: creation date)
_TODAY = datetime.now(UTC).strftime("%Y-%m-%d")

# Mapping of markdown heading text (lowercased) to canonical narrative key names.
# Covers both CamelCase keys (from prd_render.py output) and space-separated
# forms (from hand-written PRDs/specs).  Keys must match prd_render.py.
_HEADING_TO_NARRATIVE_KEY: dict[str, str] = {
    "overview": "Overview",
    "problemstatement": "ProblemStatement",
    "problem statement": "ProblemStatement",
    "goals": "Goals",
    "userstories": "UserStories",
    "user stories": "UserStories",
    "requirements": "Requirements",
    "successmetrics": "SuccessMetrics",
    "success metrics": "SuccessMetrics",
    "architecture": "Architecture",
    "nonfunctionalrequirements": "NonFunctionalRequirements",
    "non-functional requirements": "NonFunctionalRequirements",
    "non functional requirements": "NonFunctionalRequirements",
    "openquestions": "OpenQuestions",
    "open questions": "OpenQuestions",
}


def _is_user_customized(content: str, auto_markers: tuple[str, ...]) -> bool:
    """Check if file content has been customized beyond auto-generated content.

    Returns True if the content does NOT contain any of the known auto-generation
    markers, suggesting the user has substantially rewritten the file.
    """
    return not any(marker in content for marker in auto_markers)


# Legacy underscore-prefixed alias -- extraction of the shared helper into
# ``_vbrief_build`` (#454) preserves the public surface tests import today.
_slugify = _slugify_shared


def _parse_prd_narratives(content: str) -> dict[str, str]:
    """Parse structured ## sections from PRD/SPECIFICATION markdown into narrative keys.

    Recognizes known PRD headings (both CamelCase and space-separated forms)
    and maps them to canonical narrative key names matching prd_render.py
    NARRATIVE_KEY_ORDER.

    Returns a dict of narrative_key -> section_body for recognized sections.
    """
    narratives: dict[str, str] = {}
    parts = re.split(r"^##\s+", content, flags=re.MULTILINE)

    for part in parts[1:]:  # skip preamble before first ##
        heading, _, body = part.partition("\n")
        heading = heading.strip()
        # Strip trailing auto-generated footer (--- followed by italicized note)
        body = re.sub(r"\n---\s*\n\*{1,2}[^*]+\*{1,2}\s*$", "", body)
        body = body.strip()

        if not body:
            continue

        key = _HEADING_TO_NARRATIVE_KEY.get(heading.lower())
        if key:
            narratives[key] = body

    return narratives


def _parse_roadmap_items(roadmap_path: Path) -> tuple[list[dict], dict[str, str], list[dict]]:
    """Parse ROADMAP.md and extract items as structured data.

    Returns a tuple of:
      - active items: list of dicts with keys: number, title, phase, tier.
      - phase_descriptions: dict mapping phase heading -> description text.
      - completed items: list of dicts with keys: number, title (from Completed section).
    """
    if not roadmap_path.exists():
        return [], {}, []

    content = roadmap_path.read_text(encoding="utf-8")
    items: list[dict] = []
    completed_items: list[dict] = []
    phase_descriptions: dict[str, str] = {}
    current_phase = ""
    current_tier = ""
    in_completed = False
    # Accumulate description lines between heading and first list item
    desc_lines: list[str] = []
    capturing_desc = False
    _synthetic_counter = 0

    for line in content.splitlines():
        # Detect phase headings (## Level)
        phase_match = re.match(r"^##\s+(.+)", line)
        if phase_match:
            # Save previous phase description
            if current_phase and desc_lines:
                phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
            desc_lines = []

            current_phase = phase_match.group(1).strip()
            current_tier = ""
            if "completed" in current_phase.lower():
                in_completed = True
                capturing_desc = False
            else:
                in_completed = False
                capturing_desc = True
            continue

        # Detect tier subheadings (### Level)
        tier_match = re.match(r"^###\s+(.+)", line)
        if tier_match:
            if current_phase and desc_lines and capturing_desc:
                phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
                desc_lines = []
                capturing_desc = False
            current_tier = tier_match.group(1).strip()
            continue

        # Accumulate phase description text (non-empty, non-list lines)
        if capturing_desc and not in_completed:
            stripped = line.strip()
            if stripped and not stripped.startswith("-"):
                desc_lines.append(stripped)
                continue
            if stripped.startswith("-"):
                # First list item ends description capture
                if desc_lines:
                    phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
                    desc_lines = []
                capturing_desc = False
                # Fall through to item parsing below
            else:
                # Empty line during desc capture
                if desc_lines:
                    desc_lines.append("")
                continue

        if not current_phase:
            continue

        # --- Completed section items ---
        if in_completed:
            # Match: - ~~#NNN -- Title~~ or - ~~Title~~
            comp_match = re.match(r"^-\s+~~(?:#?(\d+)\s*--?\s*)?(.+?)~~", line)
            if comp_match:
                comp_number = comp_match.group(1) or ""
                comp_title = comp_match.group(2).strip()
                completed_items.append({
                    "number": comp_number,
                    "title": comp_title,
                    "phase": current_phase,
                })
            continue

        # --- Active section items ---
        # Match GitHub issue format: - **#NNN** -- Title
        item_match = re.match(r"^-\s+\*\*#(\d+)\*\*\s+--\s+(.+)", line)
        if item_match:
            items.append({
                "number": item_match.group(1),
                "title": item_match.group(2).strip(),
                "phase": current_phase,
                "tier": current_tier,
            })
            continue

        # Match task-based format: - **`X.Y.Z`** Title  or  - `X.Y.Z` Title
        task_match = re.match(
            r"^-\s+(?:\*\*)?`([^`]+)`(?:\*\*)?\s+(.+)", line
        )
        if task_match:
            task_id = task_match.group(1).strip()
            title = task_match.group(2).strip()
            items.append({
                "number": "",
                "title": title,
                "phase": current_phase,
                "tier": current_tier,
                "task_id": task_id,
            })
            continue

        # Generic fallback: - Title (any list item under a ## heading)
        generic_match = re.match(r"^-\s+(.+)", line)
        if generic_match:
            title = generic_match.group(1).strip()
            # Skip items that look like sub-bullets or empty
            if not title:
                continue
            _synthetic_counter += 1
            items.append({
                "number": "",
                "title": title,
                "phase": current_phase,
                "tier": current_tier,
                "synthetic_id": f"roadmap-{_synthetic_counter}",
            })
            continue

    # Save final phase description
    if current_phase and desc_lines and not in_completed:
        phase_descriptions[current_phase] = "\n".join(desc_lines).strip()

    return items, phase_descriptions, completed_items


def _resolve_repo_url(spec_vbrief: dict | None) -> str:
    """Resolve the GitHub repository URL from spec_vbrief or git remote.

    Falls back to a generic issue: prefix if no repository can be determined.
    """
    # Try spec_vbrief metadata first
    if spec_vbrief:
        repo = spec_vbrief.get("vBRIEFInfo", {}).get("repository", "")
        if repo:
            return f"https://github.com/{repo}"
        # Check references for a GitHub URL pattern
        refs = spec_vbrief.get("plan", {}).get("references", [])
        for ref in refs:
            uri = ref.get("uri", "")
            if urlparse(uri).netloc in ("github.com", "www.github.com"):
                # Extract owner/repo from URL
                parts = uri.split("github.com/")[-1].split("/")
                if len(parts) >= 2:
                    return f"https://github.com/{parts[0]}/{parts[1]}"
    return ""


def _extract_tech_stack(project_content: str) -> str:
    """Extract tech stack information from PROJECT.md content.

    Looks for common patterns:
      - **Tech Stack**: value
      - ## Tech Stack\n content
      - Tech Stack: value
    Returns extracted tech stack string, or empty string if not found.
    """
    # Pattern 1: **Tech Stack**: value (bold label on a single line)
    match = re.search(
        r"\*\*Tech\s+Stack\*\*\s*:\s*(.+)", project_content, re.IGNORECASE
    )
    if match:
        return match.group(1).strip()

    # Pattern 2: ## Tech Stack section (grab lines until next ## or EOF)
    section_match = re.search(
        r"##\s+Tech\s+Stack\s*\n(.*?)(?=\n##\s|\Z)",
        project_content,
        re.IGNORECASE | re.DOTALL,
    )
    if section_match:
        section = section_match.group(1).strip()
        if section:
            return section

    # Pattern 3: plain Tech Stack: value
    plain_match = re.search(
        r"Tech\s+Stack\s*:\s*(.+)", project_content, re.IGNORECASE
    )
    if plain_match:
        return plain_match.group(1).strip()

    return ""


def _first_prose_paragraph(content: str) -> str:
    """Return the first non-empty prose paragraph from markdown content.

    Skips fenced code blocks, blank lines, markdown heading lines, and list
    items; returns the first plain paragraph it finds.  Falls back to the
    first H1 (`# Title`) heading text if no prose paragraph exists.  Returns
    the empty string if nothing usable is found.
    """
    if not content:
        return ""
    first_h1 = ""
    in_code_block = False
    paragraph_lines: list[str] = []

    def _flush() -> str:
        if paragraph_lines:
            return " ".join(paragraph_lines).strip()
        return ""

    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue
        # First H1 title (# Title). Ignore H2/H3 etc.
        if re.match(r"^#\s+", stripped) and not first_h1:
            first_h1 = re.sub(r"^#\s+", "", stripped).strip()
            continue
        # Skip other headings -- also flush any accumulated paragraph first
        if stripped.startswith("#"):
            para = _flush()
            if para:
                return para
            paragraph_lines.clear()
            continue
        # List items (unordered and ordered), blockquotes, and tables are not
        # prose paragraphs for Overview purposes.  Ordered list detection uses
        # the standard markdown pattern "N.\s" at the line start.
        if stripped.startswith(("-", "*", ">", "|")) or re.match(r"^\d+\.\s", stripped):
            para = _flush()
            if para:
                return para
            paragraph_lines.clear()
            continue
        # Empty line ends paragraph
        if not stripped:
            para = _flush()
            if para:
                return para
            paragraph_lines.clear()
            continue
        paragraph_lines.append(stripped)

    # Final paragraph at EOF
    para = _flush()
    if para:
        return para
    # Fallback to H1 title text
    return first_h1


def _derive_overview_narrative(
    spec_vbrief: dict | None,
    spec_md_content: str | None,
    project_content: str | None,
    scope_item_count: int,
) -> str:
    """Derive an Overview narrative for PROJECT-DEFINITION.vbrief.json (#417).

    D3 requires the `Overview` narrative key (after case-folding) to be
    present on `vbrief/PROJECT-DEFINITION.vbrief.json`.  Resolution order:

    1. `spec_vbrief.plan.narratives['Overview']` if present and non-empty.
    2. First prose paragraph / H1 title of `SPECIFICATION.md` (pre-sentinel).
    3. First prose paragraph / H1 title of `PROJECT.md` (pre-sentinel).
    4. Synthesized placeholder naming the scope count, telling the user how
       to fill it in.  Always non-empty so `vbrief:validate` passes D3.
    """
    # 1. spec_vbrief narratives (set by step 2b PRD/SPEC ingestion, or by the
    # caller if there was a pre-existing specification.vbrief.json).
    if spec_vbrief:
        narratives = spec_vbrief.get("plan", {}).get("narratives", {})
        if isinstance(narratives, dict):
            ov = narratives.get("Overview")
            if isinstance(ov, str) and ov.strip():
                return ov.strip()

    # 2. SPECIFICATION.md prose / title -- but only if not already a sentinel
    # stub (would happen on re-run after migration).
    if spec_md_content and DEPRECATION_SENTINEL not in spec_md_content:
        derived = _first_prose_paragraph(spec_md_content)
        if derived:
            return derived

    # 3. PROJECT.md prose / title -- same sentinel guard.
    if project_content and DEPRECATION_SENTINEL not in project_content:
        derived = _first_prose_paragraph(project_content)
        if derived:
            return derived

    # 4. Synthesized fallback.  Always non-empty so the D3 validator passes.
    if scope_item_count > 0:
        return (
            f"Project overview was not auto-derived during migration. "
            f"{scope_item_count} scope item(s) were created in vbrief/pending/. "
            f"Update vbrief/PROJECT-DEFINITION.vbrief.json narratives['Overview'] "
            f"manually to describe your project."
        )
    return (
        "Project overview was not auto-derived during migration. "
        "Update vbrief/PROJECT-DEFINITION.vbrief.json narratives['Overview'] "
        "manually to describe your project."
    )


def _build_project_definition(
    spec_vbrief: dict | None,
    project_content: str | None,
    scope_items: list[dict],
    repo_url: str = "",
    spec_md_content: str | None = None,
) -> dict:
    """Build PROJECT-DEFINITION.vbrief.json from existing sources.

    Per RFC #309 D3:
    - narratives holds project identity (overview, tech stack, architecture, risks, config)
    - items acts as a scope registry referencing individual vBRIEF files

    ``spec_md_content`` is the raw SPECIFICATION.md text (pre-sentinel) for
    Overview-narrative derivation on canonical v0.19 consumer projects that
    have no pre-existing ``specification.vbrief.json`` (#417).
    """
    narratives: dict[str, str] = {}

    # Extract from specification.vbrief.json
    if spec_vbrief:
        plan = spec_vbrief.get("plan", {})
        if isinstance(plan, dict):
            spec_narratives = plan.get("narratives", {})
            if isinstance(spec_narratives, dict):
                for key, value in spec_narratives.items():
                    if isinstance(value, str):
                        narratives[key] = value

    # Extract from PROJECT.md
    if project_content:
        narratives["ProjectConfig"] = project_content
        # Extract tech stack into its own narrative key (D3 requirement)
        tech_stack = _extract_tech_stack(project_content)
        if tech_stack:
            narratives["tech stack"] = tech_stack

    # Ensure Overview narrative is present AND non-empty so the generated
    # PROJECT-DEFINITION passes `scripts/vbrief_validate.py::
    # validate_project_definition` D3 out of the box (#417).  Case-insensitive
    # check because D3 lowers() keys before comparing to
    # PROJECT_DEF_EXPECTED_NARRATIVES = {"overview", "tech stack"}.  The
    # value-awareness matters because a pre-existing specification.vbrief.json
    # may carry an empty / whitespace-only `Overview` -- without this check,
    # that blank value would round-trip into PROJECT-DEFINITION unchanged
    # (D3 only asserts key presence, so we surface a useful narrative instead).
    overview_key = next(
        (k for k in narratives if k.lower() == "overview"), None
    )
    overview_value = narratives.get(overview_key, "") if overview_key else ""
    if not isinstance(overview_value, str) or not overview_value.strip():
        derived = _derive_overview_narrative(
            spec_vbrief, spec_md_content, project_content, len(scope_items)
        )
        if derived:
            # Keep the existing key spelling (e.g. "overview" vs "Overview")
            # if one is present so we do not create a second key that differs
            # only in case.  Default to CamelCase "Overview" for new entries.
            narratives[overview_key or "Overview"] = derived

    items: list[dict] = []
    for scope in scope_items:
        number = scope.get("number", "")
        fallback_id = scope.get("synthetic_id", scope.get("task_id", "unknown"))
        scope_id = f"scope-{number}" if number else f"scope-{fallback_id}"
        item: dict = {
            "id": scope_id,
            "title": scope.get("title", "Untitled"),
            "status": "pending",
        }
        # Origin provenance per D11
        if number:
            ref: dict = {
                "type": "github-issue",
                "id": f"#{number}",
            }
            if repo_url:
                ref["url"] = f"{repo_url}/issues/{number}"
            item["references"] = [ref]
        items.append(item)

    return {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": "Project definition -- synthesized gestalt of the project.",
        },
        "plan": {
            "title": "PROJECT-DEFINITION",
            "status": "running",
            "narratives": narratives,
            "items": items,
        },
    }


# Legacy underscore-prefixed alias -- the shared helper lives in
# ``_vbrief_build`` (#454). Tests and callers continue to import
# ``_create_scope_vbrief`` from this module.
_create_scope_vbrief = _create_scope_vbrief_shared


def _deprecation_redirect(
    original_name: str,
    pointer_target: str,
    scope_note: str,
) -> str:
    """Generate deprecation redirect content for a replaced file."""
    return (
        f"{DEPRECATION_SENTINEL}\n"
        f"# {original_name} -- DEPRECATED\n"
        f"\n"
        f"This file has been replaced by the vBRIEF-centric document model.\n"
        f"\n"
        f"**See instead:**\n"
        f"- `{pointer_target}` -- project definition and scope registry\n"
        f"- `vbrief/pending/` -- individual scope vBRIEFs (backlog)\n"
        f"- `vbrief/active/` -- in-progress scope vBRIEFs\n"
        f"\n"
        f"{scope_note}\n"
        f"\n"
        f"Migrated on {_TODAY} by `task migrate:vbrief` (RFC #309, Story #312).\n"
    )


def migrate(project_root: Path) -> tuple[bool, list[str]]:
    """Run the full migration on the given project root.

    Returns:
        (True, actions) on success -- actions is a list of human-readable lines.
        (False, errors) on failure.
    """
    actions: list[str] = []
    warnings: list[str] = []
    vbrief_dir = project_root / "vbrief"

    # ---- Step 1: Create lifecycle folders ----
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if folder.exists():
            actions.append(f"SKIP  lifecycle folder already exists: vbrief/{folder_name}/")
        else:
            folder.mkdir(parents=True, exist_ok=True)
            actions.append(f"CREATE lifecycle folder: vbrief/{folder_name}/")

    # ---- Step 2: Read existing sources ----
    spec_vbrief_path = vbrief_dir / "specification.vbrief.json"
    spec_vbrief: dict | None = None
    if spec_vbrief_path.exists():
        try:
            spec_vbrief = json.loads(spec_vbrief_path.read_text(encoding="utf-8"))
            actions.append("READ  vbrief/specification.vbrief.json")
        except json.JSONDecodeError as exc:
            return False, [f"ERROR: invalid JSON in specification.vbrief.json: {exc}"]
    else:
        actions.append("SKIP  vbrief/specification.vbrief.json not found")

    spec_md_path = project_root / "SPECIFICATION.md"
    spec_md_content: str | None = None
    if spec_md_path.exists():
        spec_md_content = spec_md_path.read_text(encoding="utf-8")
        actions.append("READ  SPECIFICATION.md")

    project_md_path = project_root / "PROJECT.md"
    project_content: str | None = None
    if project_md_path.exists():
        project_content = project_md_path.read_text(encoding="utf-8")
        actions.append("READ  PROJECT.md")

    roadmap_path = project_root / "ROADMAP.md"
    roadmap_items, phase_descriptions, completed_items = _parse_roadmap_items(roadmap_path)
    total_items = len(roadmap_items) + len(completed_items)
    if total_items:
        actions.append(
            f"READ  ROADMAP.md ({len(roadmap_items)} active, "
            f"{len(completed_items)} completed items parsed)"
        )
    else:
        actions.append("SKIP  ROADMAP.md not found or no items parsed")

    # Resolve repository URL for provenance references
    repo_url = _resolve_repo_url(spec_vbrief)

    # ---- Step 2b: Ingest PRD/SPECIFICATION structured narratives (#397) ----
    prd_path = project_root / "PRD.md"
    ingested_narratives: dict[str, str] = {}

    if prd_path.exists():
        prd_content = prd_path.read_text(encoding="utf-8")
        actions.append("READ  PRD.md")
        ingested_narratives.update(_parse_prd_narratives(prd_content))

    if spec_md_content and DEPRECATION_SENTINEL not in spec_md_content:
        spec_parsed = _parse_prd_narratives(spec_md_content)
        # SPECIFICATION.md sections take priority over PRD.md for overlaps
        ingested_narratives.update(spec_parsed)

    if ingested_narratives:
        # Ensure spec_vbrief structure exists
        if spec_vbrief is None:
            spec_vbrief = {
                "vBRIEFInfo": {"version": "0.5", "description": "Specification"},
                "plan": {
                    "title": "Specification",
                    "status": "approved",
                    "narratives": {},
                    "items": [],
                },
            }

        existing = spec_vbrief.setdefault("plan", {}).setdefault("narratives", {})
        ingested_keys: list[str] = []
        for key, value in ingested_narratives.items():
            if key not in existing:
                existing[key] = value
                ingested_keys.append(key)

        if ingested_keys:
            spec_vbrief_path.parent.mkdir(parents=True, exist_ok=True)
            spec_vbrief_path.write_text(
                json.dumps(spec_vbrief, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            actions.append(
                f"INGEST narratives into specification.vbrief.json: "
                f"{', '.join(sorted(ingested_keys))}"
            )

    # ---- Step 3: Generate PROJECT-DEFINITION.vbrief.json ----
    proj_def_path = vbrief_dir / "PROJECT-DEFINITION.vbrief.json"
    if proj_def_path.exists():
        actions.append("SKIP  PROJECT-DEFINITION.vbrief.json already exists (idempotent)")
    else:
        all_items = roadmap_items + completed_items
        proj_def = _build_project_definition(
            spec_vbrief,
            project_content,
            all_items,
            repo_url=repo_url,
            spec_md_content=spec_md_content,
        )
        proj_def_path.write_text(
            json.dumps(proj_def, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        actions.append("CREATE vbrief/PROJECT-DEFINITION.vbrief.json")

    # ---- Step 4: Convert roadmap items to pending/ vBRIEFs ----
    for item in roadmap_items:
        number = item.get("number", "")
        slug = _slugify(item.get("title", "untitled"))
        # Build filename: use issue number, task_id, or synthetic_id
        item_id = number or item.get("task_id", "") or item.get("synthetic_id", "")
        id_part = _slugify(item_id.replace(".", "-")) if item_id else slug[:20]
        filename = f"{_TODAY}-{id_part}-{slug}.vbrief.json"
        target_path = vbrief_dir / "pending" / filename
        phase_desc = phase_descriptions.get(item.get("phase", ""), "")

        if target_path.exists():
            actions.append(f"SKIP  pending/{filename} already exists (idempotent)")
            continue

        # Check if any existing file references this issue number
        if number:
            existing = _find_existing_scope_vbrief(vbrief_dir, number)
            if existing:
                actions.append(
                    f"SKIP  #{number} already has scope vBRIEF: "
                    f"{existing.relative_to(vbrief_dir)}"
                )
                continue

        scope_vbrief = _create_scope_vbrief(
            item, repo_url=repo_url, phase_description=phase_desc
        )
        target_path.write_text(
            json.dumps(scope_vbrief, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        label = f"#{number}" if number else item.get("task_id", slug)
        actions.append(f"CREATE pending/{filename} ({label})")

    # ---- Step 4b: Convert completed items to completed/ vBRIEFs ----
    for item in completed_items:
        number = item.get("number", "")
        slug = _slugify(item.get("title", "untitled"))
        id_part = _slugify(number) if number else slug[:20]
        filename = f"{_TODAY}-{id_part}-{slug}.vbrief.json"
        target_path = vbrief_dir / "completed" / filename

        if target_path.exists():
            actions.append(f"SKIP  completed/{filename} already exists (idempotent)")
            continue

        scope_vbrief = _create_scope_vbrief(item, repo_url=repo_url, status="completed")
        target_path.write_text(
            json.dumps(scope_vbrief, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        label = f"#{number}" if number else slug
        actions.append(f"CREATE completed/{filename} ({label})")

    # ---- Step 5: Deprecation redirects ----
    if spec_md_path.exists():
        if spec_md_content and DEPRECATION_SENTINEL in spec_md_content:
            actions.append("SKIP  SPECIFICATION.md already has deprecation redirect")
        else:
            # Check for user customization
            if spec_md_content and _is_user_customized(spec_md_content, _SPEC_AUTO_MARKERS):
                preserved = _fold_custom_content(
                    proj_def_path, "SpecificationContent", spec_md_content or ""
                )
                if preserved:
                    warnings.append(
                        "WARNING: SPECIFICATION.md appears user-customized. "
                        "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                    )
                else:
                    return False, [
                        "ERROR: SPECIFICATION.md appears user-customized but content could not "
                        "be preserved in PROJECT-DEFINITION.vbrief.json. Fix the project "
                        "definition file structure and re-run to prevent data loss."
                    ]

            redirect = _deprecation_redirect(
                "SPECIFICATION.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For scope details, see individual vBRIEF files in the lifecycle folders.",
            )
            spec_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE SPECIFICATION.md with deprecation redirect")

    if project_md_path.exists():
        if project_content and DEPRECATION_SENTINEL in project_content:
            actions.append("SKIP  PROJECT.md already has deprecation redirect")
        else:
            # Check for user customization -- note: PROJECT.md content is already
            # captured in narratives["ProjectConfig"] by _build_project_definition (step 3),
            # so the fold here is a safety net only.
            if project_content and _is_user_customized(project_content, _PROJECT_AUTO_MARKERS):
                warnings.append(
                    "WARNING: PROJECT.md appears user-customized. "
                    "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                )

            redirect = _deprecation_redirect(
                "PROJECT.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For project configuration, see the narratives section.",
            )
            project_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE PROJECT.md with deprecation redirect")

    # ---- Report ----
    for w in warnings:
        actions.append(w)

    return True, actions


def _edge_nodes(edge: dict) -> tuple[str, str]:
    """Return (from_id, to_id) for a vBRIEF edge, reading both dialects.

    The canonical v0.5 key names are ``from`` / ``to``, but earlier speckit
    drafts used ``source`` / ``target``.  Prefer the canonical keys when they
    are populated and fall back to the legacy keys so a single translator can
    handle both shapes (covers the #458 migrate_vbrief.py touchpoint).
    """
    if not isinstance(edge, dict):
        return "", ""
    src = edge.get("from") or edge.get("source", "")
    tgt = edge.get("to") or edge.get("target", "")
    return str(src or ""), str(tgt or "")


def _dependencies_for_item(item_id: str, edges: list[dict]) -> list[str]:
    """Return the list of item IDs that block ``item_id`` (bilingual reader).

    An edge with ``type == 'blocks'`` and target equal to ``item_id`` means the
    edge's source blocks this item — so the source is a dependency of it.
    """
    deps: list[str] = []
    for edge in edges or []:
        if not isinstance(edge, dict):
            continue
        if edge.get("type", "") != "blocks":
            continue
        src, tgt = _edge_nodes(edge)
        if tgt == item_id and src and src not in deps:
            deps.append(src)
    return deps


def _speckit_ip_slug(title: str, item_id: str) -> str:
    """Return a slug for a speckit IP item filename.

    Strips any leading ``IP-N:`` / ``IP\u00a0N:`` / ``IPN-`` prefix so the slug
    focuses on the descriptive part (e.g. ``IP-3: Implement data layer`` ->
    ``implement-data-layer``).  Falls back to the item_id slug when no title
    is available.
    """
    source = (title or item_id or "").strip()
    # Strip leading IP-N: or IP N: or IPN- prefixes (case-insensitive).
    source = re.sub(r"^\s*IP[\s-]*\d+\s*[:\-]\s*", "", source, flags=re.IGNORECASE)
    slug = _slugify(source)
    return slug or _slugify(item_id) or "ip-phase"


def _speckit_ip_index(item: dict, fallback_index: int) -> int:
    """Derive the numeric IP index for a speckit plan item.

    Resolution order:
    1. Trailing digits on ``item.id`` (e.g. ``ip-3``, ``IP-12``, ``t4`` -> 3/12/4).
    2. Leading digits on ``item.title`` (e.g. ``IP-7: Foo`` -> 7).
    3. ``fallback_index`` (1-based position in the items list).
    """
    item_id = str(item.get("id", "") or "")
    tail = re.search(r"(\d+)\s*$", item_id)
    if tail:
        return int(tail.group(1))
    title = str(item.get("title", "") or "")
    lead = re.search(r"IP[\s-]*(\d+)", title, flags=re.IGNORECASE)
    if lead:
        return int(lead.group(1))
    return fallback_index


def _create_speckit_scope_vbrief(
    item: dict,
    *,
    ip_index: int,
    dependencies: list[str],
    spec_ref: str,
) -> dict:
    """Build a Phase 4 scope vBRIEF dict for a speckit implementation phase.

    Populates the canonical narrative keys (``Description``, ``Acceptance``,
    ``Traces``), writes ``plan.metadata.dependencies`` at the plan level, and
    links back to the parent ``specification.vbrief.json`` via a
    ``x-vbrief/plan`` reference.
    """
    title = str(item.get("title", f"IP-{ip_index}") or f"IP-{ip_index}")
    narrative = item.get("narrative") or {}
    if not isinstance(narrative, dict):
        narrative = {}

    def _pick(*keys: str, default: str = "") -> str:
        for key in keys:
            value = narrative.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
        return default

    description = _pick("Description", "Summary", default=title)
    acceptance = _pick("Acceptance", "AcceptanceCriteria", default="")
    traces = _pick("Traces", "Trace", "Requirements", default=f"IP-{ip_index}")

    default_acceptance = (
        f"Acceptance criteria for IP-{ip_index} "
        f"(copy from specification.vbrief.json)."
    )
    narratives: dict[str, str] = {
        "Description": description,
        "Acceptance": acceptance or default_acceptance,
        "Traces": traces,
    }
    # Preserve optional canonical-adjacent keys if present.
    for extra in ("Phase", "PhaseDescription", "Tier"):
        value = narrative.get(extra)
        if isinstance(value, str) and value.strip():
            narratives[extra] = value.strip()

    references = [
        {"type": "x-vbrief/plan", "url": spec_ref},
    ]
    # Copy any origin-provenance refs from the item (e.g. github-issue).
    for ref in item.get("references", []) or []:
        if isinstance(ref, dict) and ref.get("type") != "x-vbrief/plan":
            references.append(ref)

    plan: dict = {
        "title": title,
        "status": "pending",
        "narratives": narratives,
        "items": [],
        "references": references,
    }
    if dependencies:
        plan["metadata"] = {"dependencies": list(dependencies)}

    return {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": f"Scope vBRIEF for speckit IP-{ip_index}",
        },
        "plan": plan,
    }


def migrate_speckit_plan(
    plan_path: Path,
    *,
    pending_dir: Path | None = None,
    date: str | None = None,
    spec_ref: str = "../specification.vbrief.json",
) -> tuple[bool, list[str]]:
    """Translate a speckit-shaped ``plan.vbrief.json`` into scope vBRIEFs.

    Each ``plan.items`` entry becomes a file in ``pending_dir`` named
    ``YYYY-MM-DD-ip<NNN>-<slug>.vbrief.json``.  Dependencies are read from
    ``plan.edges`` with ``type == 'blocks'`` using the bilingual edge reader
    (``from/to`` preferred, ``source/target`` fallback) so both legacy and
    canonical edge shapes translate correctly.  The source ``plan.vbrief.json``
    is rewritten to the canonical session-todo scaffold described in
    ``vbrief/vbrief.md#planvbriefjson`` (empty items, session-level title).

    Returns ``(ok, actions)`` where ``actions`` is a human-readable list.
    """
    actions: list[str] = []
    if not plan_path.is_file():
        return False, [f"ERROR: plan.vbrief.json not found at {plan_path}"]

    try:
        plan_data = json.loads(plan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return False, [f"ERROR: invalid JSON in {plan_path.name}: {exc}"]

    plan = plan_data.get("plan", {}) if isinstance(plan_data, dict) else {}
    items = plan.get("items", []) if isinstance(plan, dict) else []
    edges = plan.get("edges", []) if isinstance(plan, dict) else []

    if not items:
        return False, [
            "ERROR: plan.vbrief.json has no items to migrate (empty speckit plan?)"
        ]

    pending_dir = pending_dir or (plan_path.parent / "pending")
    pending_dir.mkdir(parents=True, exist_ok=True)
    date = date or _TODAY

    created_paths: list[Path] = []
    for idx, item in enumerate(items, start=1):
        if not isinstance(item, dict):
            continue
        ip_index = _speckit_ip_index(item, idx)
        item_id = str(item.get("id", "") or f"ip-{ip_index}")
        dependencies = _dependencies_for_item(item_id, edges)
        slug = _speckit_ip_slug(str(item.get("title", "")), item_id)
        ip_token = f"ip{ip_index:03d}"
        filename = f"{date}-{ip_token}-{slug}.vbrief.json"
        target = pending_dir / filename
        if target.exists():
            actions.append(f"SKIP   pending/{filename} already exists")
            created_paths.append(target)
            continue
        scope = _create_speckit_scope_vbrief(
            item,
            ip_index=ip_index,
            dependencies=dependencies,
            spec_ref=spec_ref,
        )
        target.write_text(
            json.dumps(scope, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        actions.append(f"CREATE pending/{filename} (IP-{ip_index})")
        created_paths.append(target)

    # Rewrite plan.vbrief.json to the session-todo scaffold, preserving the
    # envelope title so context isn't lost.
    envelope = plan_data.get("vBRIEFInfo", {}) if isinstance(plan_data, dict) else {}
    envelope.setdefault("version", "0.5")
    envelope["description"] = (
        "Session-level tactical plan (migrated from speckit plan). "
        "Scope vBRIEFs live in vbrief/pending/."
    )
    session_plan = {
        "vBRIEFInfo": envelope,
        "plan": {
            "title": str(plan.get("title", "Session plan")) or "Session plan",
            "status": "running",
            "items": [],
        },
    }
    plan_path.write_text(
        json.dumps(session_plan, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    actions.append(f"REWRITE {plan_path.name} -> session-todo scaffold")
    return True, actions


def _find_existing_scope_vbrief(vbrief_dir: Path, issue_number: str) -> Path | None:
    """Check if any existing vBRIEF in lifecycle folders references the issue."""
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if not folder.exists():
            continue
        for fpath in folder.glob("*.vbrief.json"):
            try:
                data = json.loads(fpath.read_text(encoding="utf-8"))
                refs = data.get("plan", {}).get("references", [])
                for ref in refs:
                    if ref.get("id") == f"#{issue_number}":
                        return fpath
            except (json.JSONDecodeError, AttributeError):
                continue
    return None


def _fold_custom_content(proj_def_path: Path, key: str, content: str) -> bool:
    """Fold custom content into PROJECT-DEFINITION.vbrief.json narratives.

    Returns True if content was successfully preserved, False otherwise.
    """
    if not proj_def_path.exists():
        return False
    try:
        data = json.loads(proj_def_path.read_text(encoding="utf-8"))
        data.setdefault("plan", {}).setdefault("narratives", {})[key] = content
        proj_def_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        return True
    except (json.JSONDecodeError, AttributeError):
        return False


def main() -> int:
    """Entry point for the migration script."""
    args = list(sys.argv[1:])

    # --speckit-plan <path> subcommand: convert a speckit-shaped plan.vbrief.json
    # into per-IP scope vBRIEFs in ``<plan dir>/pending/`` (#436, #458).
    if args and args[0] == "--speckit-plan":
        if len(args) < 2:
            print(
                "ERROR: --speckit-plan requires a path argument",
                file=sys.stderr,
            )
            return 2
        plan_path = Path(args[1]).resolve()
        print(f"Migrating speckit plan at: {plan_path}")
        print("=" * 60)
        ok, messages = migrate_speckit_plan(plan_path)
        for msg in messages:
            print(f"  {msg}")
        print("=" * 60)
        if ok:
            print("speckit plan migration completed successfully.")
            return 0
        print("speckit plan migration FAILED.", file=sys.stderr)
        return 1

    project_root = Path(args[0]).resolve() if args else Path.cwd()

    if not project_root.is_dir():
        print(f"ERROR: {project_root} is not a directory", file=sys.stderr)
        return 1

    print(f"Migrating project at: {project_root}")
    print("=" * 60)

    ok, messages = migrate(project_root)

    for msg in messages:
        print(f"  {msg}")

    print("=" * 60)
    if ok:
        print("Migration completed successfully.")
        return 0
    print("Migration FAILED.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
