#!/usr/bin/env python3
"""
migrate_vbrief.py -- Migrate a Deft project to the vBRIEF-centric document model.

Converts existing SPECIFICATION.md + specification.vbrief.json + PROJECT.md +
ROADMAP.md into the new lifecycle folder structure defined by RFC #309.

Usage:
    uv run python scripts/migrate_vbrief.py [project_root]

    project_root -- path to the project root (default: current working directory)

Exit codes:
    0 -- migration completed successfully
    1 -- migration failed (errors printed to stderr)

Story: #312 (Phase 2 vBRIEF Architecture Cutover)
"""

from __future__ import annotations

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

# Lifecycle folders per RFC #309 D13
LIFECYCLE_FOLDERS = ("proposed", "pending", "active", "completed", "cancelled")

# Deprecation redirect sentinel per Story S (#334)
DEPRECATION_SENTINEL = "<!-- deft:deprecated-redirect -->"

# Known auto-generated markers for detecting user customization
_SPEC_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
    "spec_render.py",
)
_PROJECT_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
)

# Date for migration-created vBRIEF filenames (D7: creation date)
_TODAY = datetime.now(UTC).strftime("%Y-%m-%d")


def _is_user_customized(content: str, auto_markers: tuple[str, ...]) -> bool:
    """Check if file content has been customized beyond auto-generated content.

    Returns True if the content does NOT contain any of the known auto-generation
    markers, suggesting the user has substantially rewritten the file.
    """
    return not any(marker in content for marker in auto_markers)


def _slugify(text: str) -> str:
    """Convert a title to a filename-safe slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug[:60].strip("-")


def _parse_roadmap_items(roadmap_path: Path) -> tuple[list[dict], dict[str, str], list[dict]]:
    """Parse ROADMAP.md and extract items as structured data.

    Returns a tuple of:
      - active items: list of dicts with keys: number, title, phase, tier.
      - phase_descriptions: dict mapping phase heading -> description text.
      - completed items: list of dicts with keys: number, title (from Completed section).
    """
    if not roadmap_path.exists():
        return [], {}, []

    content = roadmap_path.read_text(encoding="utf-8")
    items: list[dict] = []
    completed_items: list[dict] = []
    phase_descriptions: dict[str, str] = {}
    current_phase = ""
    current_tier = ""
    in_completed = False
    # Accumulate description lines between heading and first list item
    desc_lines: list[str] = []
    capturing_desc = False
    _synthetic_counter = 0

    for line in content.splitlines():
        # Detect phase headings (## Level)
        phase_match = re.match(r"^##\s+(.+)", line)
        if phase_match:
            # Save previous phase description
            if current_phase and desc_lines:
                phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
            desc_lines = []

            current_phase = phase_match.group(1).strip()
            current_tier = ""
            if "completed" in current_phase.lower():
                in_completed = True
                capturing_desc = False
            else:
                in_completed = False
                capturing_desc = True
            continue

        # Detect tier subheadings (### Level)
        tier_match = re.match(r"^###\s+(.+)", line)
        if tier_match:
            if current_phase and desc_lines and capturing_desc:
                phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
                desc_lines = []
                capturing_desc = False
            current_tier = tier_match.group(1).strip()
            continue

        # Accumulate phase description text (non-empty, non-list lines)
        if capturing_desc and not in_completed:
            stripped = line.strip()
            if stripped and not stripped.startswith("-"):
                desc_lines.append(stripped)
                continue
            if stripped.startswith("-"):
                # First list item ends description capture
                if desc_lines:
                    phase_descriptions[current_phase] = "\n".join(desc_lines).strip()
                    desc_lines = []
                capturing_desc = False
                # Fall through to item parsing below
            else:
                # Empty line during desc capture
                if desc_lines:
                    desc_lines.append("")
                continue

        if not current_phase:
            continue

        # --- Completed section items ---
        if in_completed:
            # Match: - ~~#NNN -- Title~~ or - ~~Title~~
            comp_match = re.match(r"^-\s+~~(?:#?(\d+)\s*--?\s*)?(.+?)~~", line)
            if comp_match:
                comp_number = comp_match.group(1) or ""
                comp_title = comp_match.group(2).strip()
                completed_items.append({
                    "number": comp_number,
                    "title": comp_title,
                    "phase": current_phase,
                })
            continue

        # --- Active section items ---
        # Match GitHub issue format: - **#NNN** -- Title
        item_match = re.match(r"^-\s+\*\*#(\d+)\*\*\s+--\s+(.+)", line)
        if item_match:
            items.append({
                "number": item_match.group(1),
                "title": item_match.group(2).strip(),
                "phase": current_phase,
                "tier": current_tier,
            })
            continue

        # Match task-based format: - **`X.Y.Z`** Title  or  - `X.Y.Z` Title
        task_match = re.match(
            r"^-\s+(?:\*\*)?`([^`]+)`(?:\*\*)?\s+(.+)", line
        )
        if task_match:
            task_id = task_match.group(1).strip()
            title = task_match.group(2).strip()
            items.append({
                "number": "",
                "title": title,
                "phase": current_phase,
                "tier": current_tier,
                "task_id": task_id,
            })
            continue

        # Generic fallback: - Title (any list item under a ## heading)
        generic_match = re.match(r"^-\s+(.+)", line)
        if generic_match:
            title = generic_match.group(1).strip()
            # Skip items that look like sub-bullets or empty
            if not title:
                continue
            _synthetic_counter += 1
            items.append({
                "number": "",
                "title": title,
                "phase": current_phase,
                "tier": current_tier,
                "synthetic_id": f"roadmap-{_synthetic_counter}",
            })
            continue

    # Save final phase description
    if current_phase and desc_lines and not in_completed:
        phase_descriptions[current_phase] = "\n".join(desc_lines).strip()

    return items, phase_descriptions, completed_items


def _resolve_repo_url(spec_vbrief: dict | None) -> str:
    """Resolve the GitHub repository URL from spec_vbrief or git remote.

    Falls back to a generic issue: prefix if no repository can be determined.
    """
    # Try spec_vbrief metadata first
    if spec_vbrief:
        repo = spec_vbrief.get("vBRIEFInfo", {}).get("repository", "")
        if repo:
            return f"https://github.com/{repo}"
        # Check references for a GitHub URL pattern
        refs = spec_vbrief.get("plan", {}).get("references", [])
        for ref in refs:
            uri = ref.get("uri", "")
            if "github.com" in uri:
                # Extract owner/repo from URL
                parts = uri.split("github.com/")[-1].split("/")
                if len(parts) >= 2:
                    return f"https://github.com/{parts[0]}/{parts[1]}"
    return ""


def _extract_tech_stack(project_content: str) -> str:
    """Extract tech stack information from PROJECT.md content.

    Looks for common patterns:
      - **Tech Stack**: value
      - ## Tech Stack\n content
      - Tech Stack: value
    Returns extracted tech stack string, or empty string if not found.
    """
    # Pattern 1: **Tech Stack**: value (bold label on a single line)
    match = re.search(
        r"\*\*Tech\s+Stack\*\*\s*:\s*(.+)", project_content, re.IGNORECASE
    )
    if match:
        return match.group(1).strip()

    # Pattern 2: ## Tech Stack section (grab lines until next ## or EOF)
    section_match = re.search(
        r"##\s+Tech\s+Stack\s*\n(.*?)(?=\n##\s|\Z)",
        project_content,
        re.IGNORECASE | re.DOTALL,
    )
    if section_match:
        section = section_match.group(1).strip()
        if section:
            return section

    # Pattern 3: plain Tech Stack: value
    plain_match = re.search(
        r"Tech\s+Stack\s*:\s*(.+)", project_content, re.IGNORECASE
    )
    if plain_match:
        return plain_match.group(1).strip()

    return ""


def _build_project_definition(
    spec_vbrief: dict | None,
    project_content: str | None,
    scope_items: list[dict],
    repo_url: str = "",
) -> dict:
    """Build PROJECT-DEFINITION.vbrief.json from existing sources.

    Per RFC #309 D3:
    - narratives holds project identity (overview, tech stack, architecture, risks, config)
    - items acts as a scope registry referencing individual vBRIEF files
    """
    narratives: dict[str, str] = {}

    # Extract from specification.vbrief.json
    if spec_vbrief:
        plan = spec_vbrief.get("plan", {})
        if isinstance(plan, dict):
            spec_narratives = plan.get("narratives", {})
            if isinstance(spec_narratives, dict):
                for key, value in spec_narratives.items():
                    if isinstance(value, str):
                        narratives[key] = value

    # Extract from PROJECT.md
    if project_content:
        narratives["ProjectConfig"] = project_content
        # Extract tech stack into its own narrative key (D3 requirement)
        tech_stack = _extract_tech_stack(project_content)
        if tech_stack:
            narratives["tech stack"] = tech_stack

    items: list[dict] = []
    for scope in scope_items:
        number = scope.get("number", "")
        fallback_id = scope.get("synthetic_id", scope.get("task_id", "unknown"))
        scope_id = f"scope-{number}" if number else f"scope-{fallback_id}"
        item: dict = {
            "id": scope_id,
            "title": scope.get("title", "Untitled"),
            "status": "pending",
        }
        # Origin provenance per D11
        if number:
            ref: dict = {
                "type": "github-issue",
                "id": f"#{number}",
            }
            if repo_url:
                ref["url"] = f"{repo_url}/issues/{number}"
            item["references"] = [ref]
        items.append(item)

    return {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": "Project definition -- synthesized gestalt of the project.",
        },
        "plan": {
            "title": "PROJECT-DEFINITION",
            "status": "running",
            "narratives": narratives,
            "items": items,
        },
    }


def _create_scope_vbrief(
    item: dict,
    repo_url: str = "",
    status: str = "pending",
    phase_description: str = "",
) -> dict:
    """Create an individual scope vBRIEF from a roadmap item.

    Per RFC #309 D7: filename uses creation date + descriptive slug.
    Per D11: origin provenance via references.
    """
    number = item.get("number", "")
    title = item.get("title", "Untitled")
    phase = item.get("phase", "")
    tier = item.get("tier", "")

    desc_label = f"#{number}: {title}" if number else title
    narratives: dict[str, str] = {
        "Description": title,
        "Phase": phase,
    }
    if tier:
        narratives["Tier"] = tier
    if phase_description:
        narratives["PhaseDescription"] = phase_description

    vbrief: dict = {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": f"Scope vBRIEF for {desc_label}",
        },
        "plan": {
            "title": title,
            "status": status,
            "narratives": narratives,
            "items": [],
        },
    }

    # Origin provenance per D11
    if number:
        ref: dict = {
            "type": "github-issue",
            "id": f"#{number}",
        }
        if repo_url:
            ref["url"] = f"{repo_url}/issues/{number}"
        vbrief["plan"]["references"] = [ref]

    return vbrief


def _deprecation_redirect(
    original_name: str,
    pointer_target: str,
    scope_note: str,
) -> str:
    """Generate deprecation redirect content for a replaced file."""
    return (
        f"{DEPRECATION_SENTINEL}\n"
        f"# {original_name} -- DEPRECATED\n"
        f"\n"
        f"This file has been replaced by the vBRIEF-centric document model.\n"
        f"\n"
        f"**See instead:**\n"
        f"- `{pointer_target}` -- project definition and scope registry\n"
        f"- `vbrief/pending/` -- individual scope vBRIEFs (backlog)\n"
        f"- `vbrief/active/` -- in-progress scope vBRIEFs\n"
        f"\n"
        f"{scope_note}\n"
        f"\n"
        f"Migrated on {_TODAY} by `task migrate:vbrief` (RFC #309, Story #312).\n"
    )


def migrate(project_root: Path) -> tuple[bool, list[str]]:
    """Run the full migration on the given project root.

    Returns:
        (True, actions) on success -- actions is a list of human-readable lines.
        (False, errors) on failure.
    """
    actions: list[str] = []
    warnings: list[str] = []
    vbrief_dir = project_root / "vbrief"

    # ---- Step 1: Create lifecycle folders ----
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if folder.exists():
            actions.append(f"SKIP  lifecycle folder already exists: vbrief/{folder_name}/")
        else:
            folder.mkdir(parents=True, exist_ok=True)
            actions.append(f"CREATE lifecycle folder: vbrief/{folder_name}/")

    # ---- Step 2: Read existing sources ----
    spec_vbrief_path = vbrief_dir / "specification.vbrief.json"
    spec_vbrief: dict | None = None
    if spec_vbrief_path.exists():
        try:
            spec_vbrief = json.loads(spec_vbrief_path.read_text(encoding="utf-8"))
            actions.append("READ  vbrief/specification.vbrief.json")
        except json.JSONDecodeError as exc:
            return False, [f"ERROR: invalid JSON in specification.vbrief.json: {exc}"]
    else:
        actions.append("SKIP  vbrief/specification.vbrief.json not found")

    spec_md_path = project_root / "SPECIFICATION.md"
    spec_md_content: str | None = None
    if spec_md_path.exists():
        spec_md_content = spec_md_path.read_text(encoding="utf-8")
        actions.append("READ  SPECIFICATION.md")

    project_md_path = project_root / "PROJECT.md"
    project_content: str | None = None
    if project_md_path.exists():
        project_content = project_md_path.read_text(encoding="utf-8")
        actions.append("READ  PROJECT.md")

    roadmap_path = project_root / "ROADMAP.md"
    roadmap_items, phase_descriptions, completed_items = _parse_roadmap_items(roadmap_path)
    total_items = len(roadmap_items) + len(completed_items)
    if total_items:
        actions.append(
            f"READ  ROADMAP.md ({len(roadmap_items)} active, "
            f"{len(completed_items)} completed items parsed)"
        )
    else:
        actions.append("SKIP  ROADMAP.md not found or no items parsed")

    # Resolve repository URL for provenance references
    repo_url = _resolve_repo_url(spec_vbrief)

    # ---- Step 3: Generate PROJECT-DEFINITION.vbrief.json ----
    proj_def_path = vbrief_dir / "PROJECT-DEFINITION.vbrief.json"
    if proj_def_path.exists():
        actions.append("SKIP  PROJECT-DEFINITION.vbrief.json already exists (idempotent)")
    else:
        all_items = roadmap_items + completed_items
        proj_def = _build_project_definition(
            spec_vbrief, project_content, all_items, repo_url=repo_url
        )
        proj_def_path.write_text(
            json.dumps(proj_def, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        actions.append("CREATE vbrief/PROJECT-DEFINITION.vbrief.json")

    # ---- Step 4: Convert roadmap items to pending/ vBRIEFs ----
    for item in roadmap_items:
        number = item.get("number", "")
        slug = _slugify(item.get("title", "untitled"))
        # Build filename: use issue number, task_id, or synthetic_id
        item_id = number or item.get("task_id", "") or item.get("synthetic_id", "")
        id_part = item_id.replace(".", "-") if item_id else slug[:20]
        filename = f"{_TODAY}-{id_part}-{slug}.vbrief.json"
        target_path = vbrief_dir / "pending" / filename
        phase_desc = phase_descriptions.get(item.get("phase", ""), "")

        if target_path.exists():
            actions.append(f"SKIP  pending/{filename} already exists (idempotent)")
            continue

        # Check if any existing file references this issue number
        if number:
            existing = _find_existing_scope_vbrief(vbrief_dir, number)
            if existing:
                actions.append(
                    f"SKIP  #{number} already has scope vBRIEF: "
                    f"{existing.relative_to(vbrief_dir)}"
                )
                continue

        scope_vbrief = _create_scope_vbrief(
            item, repo_url=repo_url, phase_description=phase_desc
        )
        target_path.write_text(
            json.dumps(scope_vbrief, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        label = f"#{number}" if number else item.get("task_id", slug)
        actions.append(f"CREATE pending/{filename} ({label})")

    # ---- Step 4b: Convert completed items to completed/ vBRIEFs ----
    for item in completed_items:
        number = item.get("number", "")
        slug = _slugify(item.get("title", "untitled"))
        id_part = number if number else slug[:20]
        filename = f"{_TODAY}-{id_part}-{slug}.vbrief.json"
        target_path = vbrief_dir / "completed" / filename

        if target_path.exists():
            actions.append(f"SKIP  completed/{filename} already exists (idempotent)")
            continue

        scope_vbrief = _create_scope_vbrief(item, repo_url=repo_url, status="completed")
        target_path.write_text(
            json.dumps(scope_vbrief, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        label = f"#{number}" if number else slug
        actions.append(f"CREATE completed/{filename} ({label})")

    # ---- Step 5: Deprecation redirects ----
    if spec_md_path.exists():
        if spec_md_content and DEPRECATION_SENTINEL in spec_md_content:
            actions.append("SKIP  SPECIFICATION.md already has deprecation redirect")
        else:
            # Check for user customization
            if spec_md_content and _is_user_customized(spec_md_content, _SPEC_AUTO_MARKERS):
                preserved = _fold_custom_content(
                    proj_def_path, "SpecificationContent", spec_md_content or ""
                )
                if preserved:
                    warnings.append(
                        "WARNING: SPECIFICATION.md appears user-customized. "
                        "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                    )
                else:
                    return False, [
                        "ERROR: SPECIFICATION.md appears user-customized but content could not "
                        "be preserved in PROJECT-DEFINITION.vbrief.json. Fix the project "
                        "definition file structure and re-run to prevent data loss."
                    ]

            redirect = _deprecation_redirect(
                "SPECIFICATION.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For scope details, see individual vBRIEF files in the lifecycle folders.",
            )
            spec_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE SPECIFICATION.md with deprecation redirect")

    if project_md_path.exists():
        if project_content and DEPRECATION_SENTINEL in project_content:
            actions.append("SKIP  PROJECT.md already has deprecation redirect")
        else:
            # Check for user customization -- note: PROJECT.md content is already
            # captured in narratives["ProjectConfig"] by _build_project_definition (step 3),
            # so the fold here is a safety net only.
            if project_content and _is_user_customized(project_content, _PROJECT_AUTO_MARKERS):
                warnings.append(
                    "WARNING: PROJECT.md appears user-customized. "
                    "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                )

            redirect = _deprecation_redirect(
                "PROJECT.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For project configuration, see the narratives section.",
            )
            project_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE PROJECT.md with deprecation redirect")

    # ---- Report ----
    for w in warnings:
        actions.append(w)

    return True, actions


def _find_existing_scope_vbrief(vbrief_dir: Path, issue_number: str) -> Path | None:
    """Check if any existing vBRIEF in lifecycle folders references the issue."""
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if not folder.exists():
            continue
        for fpath in folder.glob("*.vbrief.json"):
            try:
                data = json.loads(fpath.read_text(encoding="utf-8"))
                refs = data.get("plan", {}).get("references", [])
                for ref in refs:
                    if ref.get("id") == f"#{issue_number}":
                        return fpath
            except (json.JSONDecodeError, AttributeError):
                continue
    return None


def _fold_custom_content(proj_def_path: Path, key: str, content: str) -> bool:
    """Fold custom content into PROJECT-DEFINITION.vbrief.json narratives.

    Returns True if content was successfully preserved, False otherwise.
    """
    if not proj_def_path.exists():
        return False
    try:
        data = json.loads(proj_def_path.read_text(encoding="utf-8"))
        data.setdefault("plan", {}).setdefault("narratives", {})[key] = content
        proj_def_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        return True
    except (json.JSONDecodeError, AttributeError):
        return False


def main() -> int:
    """Entry point for the migration script."""
    project_root = Path(sys.argv[1]).resolve() if len(sys.argv) >= 2 else Path.cwd()

    if not project_root.is_dir():
        print(f"ERROR: {project_root} is not a directory", file=sys.stderr)
        return 1

    print(f"Migrating project at: {project_root}")
    print("=" * 60)

    ok, messages = migrate(project_root)

    for msg in messages:
        print(f"  {msg}")

    print("=" * 60)
    if ok:
        print("Migration completed successfully.")
        return 0
    print("Migration FAILED.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
